// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="MultiSine_MultiSine,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.931750,HLS_SYN_LAT=389,HLS_SYN_TPT=none,HLS_SYN_MEM=8,HLS_SYN_DSP=0,HLS_SYN_FF=654,HLS_SYN_LUT=738,HLS_VERSION=2024_2}" *)

module MultiSine (
        ap_clk,
        ap_rst_n,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 12;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
wire    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_ready;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln46_fu_335_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    ap_condition_exit_pp0_iter0_stage0_pp0_iter1_reg;
wire    ap_block_pp0_stage0_11001;
reg    ap_loop_exit_ready_delayed;
wire   [2:0] phaseInc_address0;
wire   [31:0] phaseInc_q0;
wire   [8:0] samples_address0;
wire   [2:0] accumulators_address1;
wire   [31:0] accumulators_q1;
wire   [11:0] sine_lut_address0;
wire   [23:0] sine_lut_q0;
wire   [8:0] select_ln48_fu_255_p3;
reg   [8:0] select_ln48_reg_518;
reg   [8:0] select_ln48_reg_518_pp0_iter1_reg;
reg   [8:0] select_ln48_reg_518_pp0_iter2_reg;
wire   [0:0] first_iter_0_fu_287_p2;
reg   [0:0] first_iter_0_reg_523;
reg   [2:0] accumulators_addr_reg_527;
reg   [2:0] accumulators_addr_reg_527_pp0_iter1_reg;
wire   [0:0] icmp_ln49_fu_311_p2;
reg   [0:0] icmp_ln49_reg_538;
reg   [0:0] icmp_ln49_reg_538_pp0_iter1_reg;
reg   [0:0] icmp_ln46_reg_543;
reg   [31:0] phaseInc_load_reg_547;
reg   [0:0] ap_phi_mux_icmp_ln4911_phi_fu_184_p4;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln46_fu_293_p1;
wire   [63:0] zext_ln54_fu_412_p1;
wire   [63:0] zext_ln49_fu_445_p1;
reg   [8:0] indvar_flatten5_fu_84;
wire   [8:0] add_ln46_2_fu_299_p2;
reg   [8:0] ap_sig_allocacmp_indvar_flatten5_load;
reg   [8:0] sineIdx6_fu_88;
wire   [8:0] sineIdx_fu_263_p3;
reg   [8:0] ap_sig_allocacmp_sineIdx6_load;
reg   [3:0] i7_fu_92;
wire   [3:0] i_fu_271_p3;
reg   [3:0] ap_sig_allocacmp_i7_load;
reg   [8:0] indvars_iv78_fu_96;
wire   [8:0] select_ln46_2_fu_279_p3;
reg   [8:0] ap_sig_allocacmp_indvars_iv78_load;
reg   [8:0] sineIdx_110_fu_100;
wire   [8:0] sineIdx_1_fu_305_p2;
reg   [8:0] ap_sig_allocacmp_sineIdx_110_load;
reg   [3:0] add_ln4612_fu_104;
wire   [3:0] add_ln46_fu_317_p2;
reg   [3:0] ap_sig_allocacmp_add_ln4612_load;
reg   [8:0] add_ln46_113_fu_108;
wire   [8:0] add_ln46_1_fu_323_p2;
reg   [8:0] ap_sig_allocacmp_add_ln46_113_load;
reg   [8:0] add_ln5114_fu_112;
wire   [8:0] add_ln51_fu_329_p2;
reg   [8:0] ap_sig_allocacmp_add_ln5114_load;
reg   [31:0] accumulators_load19_fu_116;
reg   [31:0] empty_fu_120;
wire   [31:0] add_ln51_1_fu_397_p2;
reg    accumulators_ce1_local;
reg    accumulators_we0_local;
wire   [31:0] add_ln49_fu_433_p2;
reg    accumulators_ce0_local;
reg    phaseInc_ce0_local;
reg    sine_lut_ce0_local;
reg    samples_we0_local;
reg    samples_ce0_local;
wire   [11:0] address_fu_402_p4;
wire   [31:0] shl_ln49_fu_417_p2;
wire   [31:0] shl_ln49_1_fu_422_p2;
wire   [31:0] sub_ln49_fu_427_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_118;
reg    ap_condition_402;
reg    ap_condition_405;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 indvar_flatten5_fu_84 = 9'd0;
#0 sineIdx6_fu_88 = 9'd0;
#0 i7_fu_92 = 4'd0;
#0 indvars_iv78_fu_96 = 9'd0;
#0 sineIdx_110_fu_100 = 9'd0;
#0 add_ln4612_fu_104 = 4'd0;
#0 add_ln46_113_fu_108 = 9'd0;
#0 add_ln5114_fu_112 = 9'd0;
#0 accumulators_load19_fu_116 = 32'd0;
#0 empty_fu_120 = 32'd0;
#0 ap_done_reg = 1'b0;
end

MultiSine_accumulators_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
accumulators_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(accumulators_addr_reg_527_pp0_iter1_reg),
    .ce0(accumulators_ce0_local),
    .we0(accumulators_we0_local),
    .d0(add_ln49_fu_433_p2),
    .address1(accumulators_address1),
    .ce1(accumulators_ce1_local),
    .q1(accumulators_q1)
);

MultiSine_sine_lut_ROM_AUTO_1R #(
    .DataWidth( 24 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
sine_lut_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(sine_lut_address0),
    .ce0(sine_lut_ce0_local),
    .q0(sine_lut_q0)
);

MultiSine_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .phaseInc_address0(phaseInc_address0),
    .phaseInc_ce0(phaseInc_ce0_local),
    .phaseInc_q0(phaseInc_q0),
    .samples_address0(samples_address0),
    .samples_ce0(samples_ce0_local),
    .samples_we0(samples_we0_local),
    .samples_d0(sine_lut_q0),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

MultiSine_flow_control_loop_delay_pipe flow_control_loop_delay_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(1'b1),
    .ap_loop_exit_ready_delayed(ap_loop_exit_ready_delayed)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_118)) begin
        add_ln4612_fu_104 <= add_ln46_fu_317_p2;
    end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_118)) begin
    add_ln46_113_fu_108 <= add_ln46_1_fu_323_p2;
end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_118)) begin
    add_ln5114_fu_112 <= add_ln51_fu_329_p2;
end
end

always @ (posedge ap_clk) begin
if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b0))) begin
    ap_loop_exit_ready_pp0_iter4_reg <= 1'b0;
end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
    ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
end
end

always @ (posedge ap_clk) begin
if ((1'b0 == ap_block_pp0_stage0_11001)) begin
    if ((1'b1 == ap_condition_405)) begin
        empty_fu_120 <= accumulators_q1;
    end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        empty_fu_120 <= add_ln51_1_fu_397_p2;
    end
end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_118)) begin
    i7_fu_92 <= i_fu_271_p3;
end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_118)) begin
    indvar_flatten5_fu_84 <= add_ln46_2_fu_299_p2;
end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_118)) begin
    indvars_iv78_fu_96 <= select_ln46_2_fu_279_p3;
end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_118)) begin
    sineIdx6_fu_88 <= sineIdx_fu_263_p3;
end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_118)) begin
    sineIdx_110_fu_100 <= sineIdx_1_fu_305_p2;
end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        accumulators_addr_reg_527 <= zext_ln46_fu_293_p1;
        accumulators_addr_reg_527_pp0_iter1_reg <= accumulators_addr_reg_527;
        ap_condition_exit_pp0_iter0_stage0_pp0_iter1_reg <= ap_condition_exit_pp0_iter0_stage0;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        first_iter_0_reg_523 <= first_iter_0_fu_287_p2;
        icmp_ln46_reg_543 <= icmp_ln46_fu_335_p2;
        icmp_ln49_reg_538_pp0_iter1_reg <= icmp_ln49_reg_538;
        phaseInc_load_reg_547 <= phaseInc_q0;
        select_ln48_reg_518 <= select_ln48_fu_255_p3;
        select_ln48_reg_518_pp0_iter1_reg <= select_ln48_reg_518;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (first_iter_0_reg_523 == 1'd1))) begin
        accumulators_load19_fu_116 <= accumulators_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        select_ln48_reg_518_pp0_iter2_reg <= select_ln48_reg_518_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln49_reg_538 <= icmp_ln49_fu_311_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        accumulators_ce0_local = 1'b1;
    end else begin
        accumulators_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        accumulators_ce1_local = 1'b1;
    end else begin
        accumulators_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln49_reg_538_pp0_iter1_reg == 1'd1))) begin
        accumulators_we0_local = 1'b1;
    end else begin
        accumulators_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln46_fu_335_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_exit_pp0_iter0_stage0_pp0_iter1_reg) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_delayed = 1'b1;
    end else begin
        ap_loop_exit_ready_delayed = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_402)) begin
            ap_phi_mux_icmp_ln4911_phi_fu_184_p4 = icmp_ln49_reg_538;
        end else if ((ap_loop_init == 1'b1)) begin
            ap_phi_mux_icmp_ln4911_phi_fu_184_p4 = 1'd0;
        end else begin
            ap_phi_mux_icmp_ln4911_phi_fu_184_p4 = icmp_ln49_reg_538;
        end
    end else begin
        ap_phi_mux_icmp_ln4911_phi_fu_184_p4 = icmp_ln49_reg_538;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_add_ln4612_load = 4'd1;
    end else begin
        ap_sig_allocacmp_add_ln4612_load = add_ln4612_fu_104;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_add_ln46_113_load = 9'd96;
    end else begin
        ap_sig_allocacmp_add_ln46_113_load = add_ln46_113_fu_108;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_add_ln5114_load = 9'd48;
    end else begin
        ap_sig_allocacmp_add_ln5114_load = add_ln5114_fu_112;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i7_load = 4'd0;
    end else begin
        ap_sig_allocacmp_i7_load = i7_fu_92;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten5_load = 9'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten5_load = indvar_flatten5_fu_84;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvars_iv78_load = 9'd48;
    end else begin
        ap_sig_allocacmp_indvars_iv78_load = indvars_iv78_fu_96;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_sineIdx6_load = 9'd0;
    end else begin
        ap_sig_allocacmp_sineIdx6_load = sineIdx6_fu_88;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_sineIdx_110_load = 9'd0;
    end else begin
        ap_sig_allocacmp_sineIdx_110_load = sineIdx_110_fu_100;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        phaseInc_ce0_local = 1'b1;
    end else begin
        phaseInc_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)))) begin
        samples_ce0_local = 1'b1;
    end else begin
        samples_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        samples_we0_local = 1'b1;
    end else begin
        samples_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        sine_lut_ce0_local = 1'b1;
    end else begin
        sine_lut_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign accumulators_address1 = zext_ln46_fu_293_p1;

assign add_ln46_1_fu_323_p2 = (select_ln46_2_fu_279_p3 + 9'd48);

assign add_ln46_2_fu_299_p2 = (ap_sig_allocacmp_indvar_flatten5_load + 9'd1);

assign add_ln46_fu_317_p2 = (i_fu_271_p3 + 4'd1);

assign add_ln49_fu_433_p2 = (accumulators_load19_fu_116 + sub_ln49_fu_427_p2);

assign add_ln51_1_fu_397_p2 = (phaseInc_load_reg_547 + empty_fu_120);

assign add_ln51_fu_329_p2 = (sineIdx_fu_263_p3 + 9'd48);

assign address_fu_402_p4 = {{add_ln51_1_fu_397_p2[31:20]}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_118 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_402 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln46_reg_543 == 1'd0));
end

always @ (*) begin
    ap_condition_405 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (first_iter_0_reg_523 == 1'd1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign first_iter_0_fu_287_p2 = ((select_ln48_fu_255_p3 == sineIdx_fu_263_p3) ? 1'b1 : 1'b0);

assign i_fu_271_p3 = ((ap_phi_mux_icmp_ln4911_phi_fu_184_p4[0:0] == 1'b1) ? ap_sig_allocacmp_add_ln4612_load : ap_sig_allocacmp_i7_load);

assign icmp_ln46_fu_335_p2 = ((ap_sig_allocacmp_indvar_flatten5_load == 9'd383) ? 1'b1 : 1'b0);

assign icmp_ln49_fu_311_p2 = ((sineIdx_1_fu_305_p2 == select_ln46_2_fu_279_p3) ? 1'b1 : 1'b0);

assign phaseInc_address0 = zext_ln46_fu_293_p1;

assign samples_address0 = zext_ln49_fu_445_p1;

assign select_ln46_2_fu_279_p3 = ((ap_phi_mux_icmp_ln4911_phi_fu_184_p4[0:0] == 1'b1) ? ap_sig_allocacmp_add_ln46_113_load : ap_sig_allocacmp_indvars_iv78_load);

assign select_ln48_fu_255_p3 = ((ap_phi_mux_icmp_ln4911_phi_fu_184_p4[0:0] == 1'b1) ? ap_sig_allocacmp_add_ln5114_load : ap_sig_allocacmp_sineIdx_110_load);

assign shl_ln49_1_fu_422_p2 = phaseInc_load_reg_547 << 32'd4;

assign shl_ln49_fu_417_p2 = phaseInc_load_reg_547 << 32'd6;

assign sineIdx_1_fu_305_p2 = (select_ln48_fu_255_p3 + 9'd1);

assign sineIdx_fu_263_p3 = ((ap_phi_mux_icmp_ln4911_phi_fu_184_p4[0:0] == 1'b1) ? ap_sig_allocacmp_add_ln5114_load : ap_sig_allocacmp_sineIdx6_load);

assign sine_lut_address0 = zext_ln54_fu_412_p1;

assign sub_ln49_fu_427_p2 = (shl_ln49_fu_417_p2 - shl_ln49_1_fu_422_p2);

assign zext_ln46_fu_293_p1 = i_fu_271_p3;

assign zext_ln49_fu_445_p1 = select_ln48_reg_518_pp0_iter2_reg;

assign zext_ln54_fu_412_p1 = address_fu_402_p4;

endmodule //MultiSine
