// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="MultiSine_MultiSine,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.006000,HLS_SYN_LAT=389,HLS_SYN_TPT=none,HLS_SYN_MEM=8,HLS_SYN_DSP=0,HLS_SYN_FF=469,HLS_SYN_LUT=518,HLS_VERSION=2024_2}" *)

module MultiSine (
        ap_clk,
        ap_rst_n,
        s_axi_BUS_A_AWVALID,
        s_axi_BUS_A_AWREADY,
        s_axi_BUS_A_AWADDR,
        s_axi_BUS_A_WVALID,
        s_axi_BUS_A_WREADY,
        s_axi_BUS_A_WDATA,
        s_axi_BUS_A_WSTRB,
        s_axi_BUS_A_ARVALID,
        s_axi_BUS_A_ARREADY,
        s_axi_BUS_A_ARADDR,
        s_axi_BUS_A_RVALID,
        s_axi_BUS_A_RREADY,
        s_axi_BUS_A_RDATA,
        s_axi_BUS_A_RRESP,
        s_axi_BUS_A_BVALID,
        s_axi_BUS_A_BREADY,
        s_axi_BUS_A_BRESP,
        interrupt
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;
parameter    C_S_AXI_BUS_A_DATA_WIDTH = 32;
parameter    C_S_AXI_BUS_A_ADDR_WIDTH = 12;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_BUS_A_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   s_axi_BUS_A_AWVALID;
output   s_axi_BUS_A_AWREADY;
input  [C_S_AXI_BUS_A_ADDR_WIDTH - 1:0] s_axi_BUS_A_AWADDR;
input   s_axi_BUS_A_WVALID;
output   s_axi_BUS_A_WREADY;
input  [C_S_AXI_BUS_A_DATA_WIDTH - 1:0] s_axi_BUS_A_WDATA;
input  [C_S_AXI_BUS_A_WSTRB_WIDTH - 1:0] s_axi_BUS_A_WSTRB;
input   s_axi_BUS_A_ARVALID;
output   s_axi_BUS_A_ARREADY;
input  [C_S_AXI_BUS_A_ADDR_WIDTH - 1:0] s_axi_BUS_A_ARADDR;
output   s_axi_BUS_A_RVALID;
input   s_axi_BUS_A_RREADY;
output  [C_S_AXI_BUS_A_DATA_WIDTH - 1:0] s_axi_BUS_A_RDATA;
output  [1:0] s_axi_BUS_A_RRESP;
output   s_axi_BUS_A_BVALID;
input   s_axi_BUS_A_BREADY;
output  [1:0] s_axi_BUS_A_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
wire    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_ready;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln58_fu_236_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    ap_condition_exit_pp0_iter0_stage0_pp0_iter1_reg;
wire    ap_block_pp0_stage0_11001;
reg    ap_condition_exit_pp0_iter0_stage0_pp0_iter2_reg;
reg    ap_loop_exit_ready_delayed;
wire   [2:0] phaseInc_address0;
wire   [31:0] phaseInc_q0;
wire   [8:0] samples_address0;
wire   [2:0] accumulators_address1;
wire   [31:0] accumulators_q1;
wire   [11:0] sine_lut_address0;
wire   [23:0] sine_lut_q0;
reg   [0:0] icmp_ln617_reg_161;
reg   [0:0] icmp_ln617_reg_161_pp0_iter1_reg;
wire   [0:0] first_iter_0_fu_206_p2;
reg   [0:0] first_iter_0_reg_366;
reg   [0:0] first_iter_0_reg_366_pp0_iter1_reg;
reg   [2:0] accumulators_addr_reg_370;
wire   [0:0] icmp_ln61_fu_230_p2;
reg   [0:0] icmp_ln61_reg_381;
reg   [0:0] icmp_ln58_reg_386;
reg   [11:0] address_reg_390;
reg   [0:0] ap_phi_mux_icmp_ln617_phi_fu_164_p4;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln61_fu_218_p1;
wire   [63:0] zext_ln66_fu_292_p1;
wire   [63:0] zext_ln61_1_fu_315_p1;
reg   [8:0] indvar_flatten3_fu_84;
wire   [8:0] add_ln58_1_fu_212_p2;
reg   [8:0] ap_sig_allocacmp_indvar_flatten3_load;
reg   [5:0] indvars_iv44_fu_88;
wire   [5:0] select_ln58_fu_275_p3;
reg   [3:0] i6_fu_92;
wire   [3:0] i_fu_224_p2;
reg   [3:0] ap_sig_allocacmp_i6_load;
reg   [5:0] add_ln588_fu_96;
wire   [5:0] add_ln58_fu_296_p2;
reg   [8:0] sineIdx5_fu_100;
wire   [8:0] sineIdx_fu_320_p2;
wire   [8:0] zext_ln58_fu_283_p1;
reg    accumulators_ce1_local;
reg    accumulators_we0_local;
wire   [31:0] add_ln63_fu_252_p2;
reg    accumulators_ce0_local;
reg    phaseInc_ce0_local;
reg    sine_lut_ce0_local;
reg    samples_we0_local;
reg    samples_ce0_local;
wire   [3:0] select_ln61_fu_198_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_195;
reg    ap_condition_356;
reg    ap_condition_118;
reg    ap_condition_363;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 indvar_flatten3_fu_84 = 9'd0;
#0 indvars_iv44_fu_88 = 6'd0;
#0 i6_fu_92 = 4'd0;
#0 add_ln588_fu_96 = 6'd0;
#0 sineIdx5_fu_100 = 9'd0;
#0 ap_done_reg = 1'b0;
end

MultiSine_accumulators_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
accumulators_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(accumulators_addr_reg_370),
    .ce0(accumulators_ce0_local),
    .we0(accumulators_we0_local),
    .d0(add_ln63_fu_252_p2),
    .address1(accumulators_address1),
    .ce1(accumulators_ce1_local),
    .q1(accumulators_q1)
);

MultiSine_sine_lut_ROM_AUTO_1R #(
    .DataWidth( 24 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
sine_lut_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(sine_lut_address0),
    .ce0(sine_lut_ce0_local),
    .q0(sine_lut_q0)
);

MultiSine_BUS_A_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_BUS_A_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_BUS_A_DATA_WIDTH ))
BUS_A_s_axi_U(
    .AWVALID(s_axi_BUS_A_AWVALID),
    .AWREADY(s_axi_BUS_A_AWREADY),
    .AWADDR(s_axi_BUS_A_AWADDR),
    .WVALID(s_axi_BUS_A_WVALID),
    .WREADY(s_axi_BUS_A_WREADY),
    .WDATA(s_axi_BUS_A_WDATA),
    .WSTRB(s_axi_BUS_A_WSTRB),
    .ARVALID(s_axi_BUS_A_ARVALID),
    .ARREADY(s_axi_BUS_A_ARREADY),
    .ARADDR(s_axi_BUS_A_ARADDR),
    .RVALID(s_axi_BUS_A_RVALID),
    .RREADY(s_axi_BUS_A_RREADY),
    .RDATA(s_axi_BUS_A_RDATA),
    .RRESP(s_axi_BUS_A_RRESP),
    .BVALID(s_axi_BUS_A_BVALID),
    .BREADY(s_axi_BUS_A_BREADY),
    .BRESP(s_axi_BUS_A_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .phaseInc_address0(phaseInc_address0),
    .phaseInc_ce0(phaseInc_ce0_local),
    .phaseInc_q0(phaseInc_q0),
    .samples_address0(samples_address0),
    .samples_ce0(samples_ce0_local),
    .samples_we0(samples_we0_local),
    .samples_d0(sine_lut_q0),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

MultiSine_flow_control_loop_delay_pipe flow_control_loop_delay_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(1'b1),
    .ap_loop_exit_ready_delayed(ap_loop_exit_ready_delayed)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if ((1'b1 == ap_condition_195)) begin
            add_ln588_fu_96 <= 6'd1;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            add_ln588_fu_96 <= add_ln58_fu_296_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b0))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= 1'b0;
    end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_118)) begin
        i6_fu_92 <= i_fu_224_p2;
    end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
    if ((1'b1 == ap_condition_363)) begin
        icmp_ln617_reg_161 <= icmp_ln61_reg_381;
    end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init == 1'b1))) begin
        icmp_ln617_reg_161 <= 1'd0;
    end
end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_118)) begin
    indvar_flatten3_fu_84 <= add_ln58_1_fu_212_p2;
end
end

always @ (posedge ap_clk) begin
if ((1'b0 == ap_block_pp0_stage0_11001)) begin
    if ((1'b1 == ap_condition_195)) begin
        indvars_iv44_fu_88 <= 6'd0;
    end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
        indvars_iv44_fu_88 <= select_ln58_fu_275_p3;
    end
end
end

always @ (posedge ap_clk) begin
if ((1'b0 == ap_block_pp0_stage0_11001)) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (first_iter_0_reg_366_pp0_iter1_reg == 1'd1))) begin
        sineIdx5_fu_100 <= zext_ln58_fu_283_p1;
    end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
        sineIdx5_fu_100 <= sineIdx_fu_320_p2;
    end
end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        accumulators_addr_reg_370 <= zext_ln61_fu_218_p1;
        address_reg_390 <= {{add_ln63_fu_252_p2[31:20]}};
        ap_condition_exit_pp0_iter0_stage0_pp0_iter1_reg <= ap_condition_exit_pp0_iter0_stage0;
        ap_condition_exit_pp0_iter0_stage0_pp0_iter2_reg <= ap_condition_exit_pp0_iter0_stage0_pp0_iter1_reg;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        first_iter_0_reg_366 <= first_iter_0_fu_206_p2;
        first_iter_0_reg_366_pp0_iter1_reg <= first_iter_0_reg_366;
        icmp_ln58_reg_386 <= icmp_ln58_fu_236_p2;
        icmp_ln617_reg_161_pp0_iter1_reg <= icmp_ln617_reg_161;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln61_reg_381 <= icmp_ln61_fu_230_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        accumulators_ce0_local = 1'b1;
    end else begin
        accumulators_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        accumulators_ce1_local = 1'b1;
    end else begin
        accumulators_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        accumulators_we0_local = 1'b1;
    end else begin
        accumulators_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln58_fu_236_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_exit_pp0_iter0_stage0_pp0_iter2_reg))) begin
        ap_loop_exit_ready_delayed = 1'b1;
    end else begin
        ap_loop_exit_ready_delayed = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_356)) begin
            ap_phi_mux_icmp_ln617_phi_fu_164_p4 = icmp_ln61_reg_381;
        end else if ((ap_loop_init == 1'b1)) begin
            ap_phi_mux_icmp_ln617_phi_fu_164_p4 = 1'd0;
        end else begin
            ap_phi_mux_icmp_ln617_phi_fu_164_p4 = icmp_ln61_reg_381;
        end
    end else begin
        ap_phi_mux_icmp_ln617_phi_fu_164_p4 = icmp_ln61_reg_381;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i6_load = 4'd0;
    end else begin
        ap_sig_allocacmp_i6_load = i6_fu_92;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten3_load = 9'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten3_load = indvar_flatten3_fu_84;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        phaseInc_ce0_local = 1'b1;
    end else begin
        phaseInc_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)))) begin
        samples_ce0_local = 1'b1;
    end else begin
        samples_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        samples_we0_local = 1'b1;
    end else begin
        samples_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        sine_lut_ce0_local = 1'b1;
    end else begin
        sine_lut_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign accumulators_address1 = zext_ln61_fu_218_p1;

assign add_ln58_1_fu_212_p2 = (ap_sig_allocacmp_indvar_flatten3_load + 9'd1);

assign add_ln58_fu_296_p2 = (select_ln58_fu_275_p3 + 6'd1);

assign add_ln63_fu_252_p2 = (phaseInc_q0 + accumulators_q1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_118 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_195 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1));
end

always @ (*) begin
    ap_condition_356 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln58_reg_386 == 1'd0));
end

always @ (*) begin
    ap_condition_363 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln58_reg_386 == 1'd0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign first_iter_0_fu_206_p2 = ((select_ln61_fu_198_p3 == 4'd0) ? 1'b1 : 1'b0);

assign i_fu_224_p2 = (select_ln61_fu_198_p3 + 4'd1);

assign icmp_ln58_fu_236_p2 = ((ap_sig_allocacmp_indvar_flatten3_load == 9'd383) ? 1'b1 : 1'b0);

assign icmp_ln61_fu_230_p2 = ((i_fu_224_p2 == 4'd8) ? 1'b1 : 1'b0);

assign phaseInc_address0 = zext_ln61_fu_218_p1;

assign samples_address0 = zext_ln61_1_fu_315_p1;

assign select_ln58_fu_275_p3 = ((icmp_ln617_reg_161_pp0_iter1_reg[0:0] == 1'b1) ? add_ln588_fu_96 : indvars_iv44_fu_88);

assign select_ln61_fu_198_p3 = ((ap_phi_mux_icmp_ln617_phi_fu_164_p4[0:0] == 1'b1) ? 4'd0 : ap_sig_allocacmp_i6_load);

assign sineIdx_fu_320_p2 = (sineIdx5_fu_100 + 9'd48);

assign sine_lut_address0 = zext_ln66_fu_292_p1;

assign zext_ln58_fu_283_p1 = select_ln58_fu_275_p3;

assign zext_ln61_1_fu_315_p1 = sineIdx5_fu_100;

assign zext_ln61_fu_218_p1 = select_ln61_fu_198_p3;

assign zext_ln66_fu_292_p1 = address_reg_390;

endmodule //MultiSine
