
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2024.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2025 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xmultisinemaster.h"

/*
* The configuration table for devices
*/

XMultisinemaster_Config XMultisinemaster_ConfigTable[XPAR_XMULTISINEMASTER_NUM_INSTANCES] =
{
	{
		XPAR_AUDIO_COMPONENTS_MULTISINEMASTER_0_DEVICE_ID,
		XPAR_AUDIO_COMPONENTS_MULTISINEMASTER_0_S_AXI_CONTROL_BASEADDR
	}
};


