
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2024.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2025 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xsimplesine.h"

/*
* The configuration table for devices
*/

XSimplesine_Config XSimplesine_ConfigTable[XPAR_XSIMPLESINE_NUM_INSTANCES] =
{
	{
		XPAR_AUDIO_COMPONENTS_SIMPLESINE_0_DEVICE_ID,
		XPAR_AUDIO_COMPONENTS_SIMPLESINE_0_S_AXI_CONTROL_BASEADDR
	}
};


