set SynModuleInfo {
  {SRCNAME SimpleSineStreamBidirectional_Pipeline_VITIS_LOOP_44_1 MODELNAME SimpleSineStreamBidirectional_Pipeline_VITIS_LOOP_44_1 RTLNAME SimpleSineStreamBidirectional_SimpleSineStreamBidirectional_Pipeline_VITIS_LOOP_44_1
    SUBMODULES {
      {MODELNAME SimpleSineStreamBidirectional_SimpleSineStreamBidirectional_Pipeline_VITIS_LOOP_44_1_sine_lut_ROM_AUTO_1R RTLNAME SimpleSineStreamBidirectional_SimpleSineStreamBidirectional_Pipeline_VITIS_LOOP_44_1_sine_lut_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME SimpleSineStreamBidirectional_flow_control_loop_pipe_sequential_init RTLNAME SimpleSineStreamBidirectional_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME SimpleSineStreamBidirectional_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME SimpleSineStreamBidirectional MODELNAME SimpleSineStreamBidirectional RTLNAME SimpleSineStreamBidirectional IS_TOP 1
    SUBMODULES {
      {MODELNAME SimpleSineStreamBidirectional_control_s_axi RTLNAME SimpleSineStreamBidirectional_control_s_axi BINDTYPE interface TYPE interface_s_axilite}
      {MODELNAME SimpleSineStreamBidirectional_regslice_both RTLNAME SimpleSineStreamBidirectional_regslice_both BINDTYPE interface TYPE adapter IMPL reg_slice}
    }
  }
}
