// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="MultiSineStream_MultiSineStream,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.657000,HLS_SYN_LAT=390,HLS_SYN_TPT=none,HLS_SYN_MEM=6,HLS_SYN_DSP=0,HLS_SYN_FF=564,HLS_SYN_LUT=607,HLS_VERSION=2024_2}" *)

module MultiSineStream (
        ap_clk,
        ap_rst_n,
        samples_TREADY,
        samples_TDATA,
        samples_TVALID,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   samples_TREADY;
output  [23:0] samples_TDATA;
output   samples_TVALID;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
wire    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_ready;
reg    ap_block_state5_pp0_stage0_iter4;
wire    regslice_both_samples_U_apdone_blk;
reg    ap_block_state6_pp0_stage0_iter5;
wire    ap_loop_exit_ready;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln46_fu_355_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
reg    ap_ready_int;
wire   [2:0] phaseInc_address0;
wire   [31:0] phaseInc_q0;
wire   [2:0] accumulators_address1;
wire   [31:0] accumulators_q1;
wire   [11:0] sine_lut_address0;
wire   [23:0] sine_lut_q0;
reg    samples_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0;
wire   [0:0] or_ln48_fu_272_p2;
reg   [0:0] or_ln48_reg_545;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] or_ln48_reg_545_pp0_iter1_reg;
reg   [2:0] accumulators_addr_reg_549;
reg   [2:0] accumulators_addr_reg_549_pp0_iter1_reg;
wire   [0:0] icmp_ln49_fu_331_p2;
reg   [0:0] icmp_ln49_reg_560;
reg   [0:0] icmp_ln49_reg_560_pp0_iter1_reg;
reg   [0:0] icmp_ln46_reg_565;
reg   [11:0] address_reg_574;
reg   [0:0] ap_phi_mux_icmp_ln4916_phi_fu_184_p4;
wire    ap_loop_init;
reg   [0:0] ap_phi_mux_first_iter_013_phi_fu_194_p4;
reg   [31:0] ap_phi_mux_accumulators_load3_phi_fu_205_p4;
reg   [31:0] ap_phi_reg_pp0_iter2_accumulators_load3_reg_202;
wire   [31:0] ap_phi_reg_pp0_iter0_accumulators_load3_reg_202;
reg   [31:0] ap_phi_reg_pp0_iter1_accumulators_load3_reg_202;
wire   [63:0] zext_ln46_fu_302_p1;
wire   [63:0] zext_ln54_fu_467_p1;
reg   [8:0] indvar_flatten7_fu_86;
wire   [8:0] add_ln46_3_fu_308_p2;
reg   [8:0] ap_sig_allocacmp_indvar_flatten7_load;
reg   [3:0] i8_fu_90;
wire   [3:0] i_fu_278_p3;
reg   [3:0] ap_sig_allocacmp_i8_load;
reg   [8:0] sineIdx9_fu_94;
wire   [8:0] sineIdx_fu_286_p3;
reg   [8:0] ap_sig_allocacmp_sineIdx9_load;
reg   [8:0] indvars_iv710_fu_98;
wire   [8:0] select_ln46_2_fu_294_p3;
reg   [8:0] ap_sig_allocacmp_indvars_iv710_load;
reg   [8:0] sineIdx_115_fu_102;
wire   [8:0] sineIdx_1_fu_325_p2;
reg   [8:0] ap_sig_allocacmp_sineIdx_115_load;
reg   [3:0] add_ln4617_fu_106;
wire   [3:0] add_ln46_fu_337_p2;
reg   [3:0] ap_sig_allocacmp_add_ln4617_load;
reg   [8:0] add_ln46_118_fu_110;
wire   [8:0] add_ln46_1_fu_343_p2;
reg   [8:0] ap_sig_allocacmp_add_ln46_118_load;
reg   [8:0] add_ln46_219_fu_114;
wire   [8:0] add_ln46_2_fu_349_p2;
reg   [8:0] ap_sig_allocacmp_add_ln46_219_load;
reg   [31:0] phaseInc_load411_fu_118;
reg   [31:0] accumulators_load112_fu_122;
reg   [31:0] conv_i_i114_fu_126;
wire   [31:0] add_ln51_fu_439_p2;
reg    ap_block_pp0_stage0_01001;
reg    phaseInc_ce0_local;
reg    accumulators_ce1_local;
reg    accumulators_we0_local;
wire   [31:0] add_ln49_fu_455_p2;
reg    accumulators_ce0_local;
reg    sine_lut_ce0_local;
wire   [8:0] select_ln48_fu_317_p3;
wire   [31:0] shl_ln49_fu_421_p2;
wire   [31:0] shl_ln49_1_fu_427_p2;
wire   [31:0] sub_ln49_fu_433_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    samples_TVALID_int_regslice;
wire    samples_TREADY_int_regslice;
wire    regslice_both_samples_U_vld_out;
reg    ap_condition_152;
reg    ap_condition_452;
reg    ap_condition_165;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 indvar_flatten7_fu_86 = 9'd0;
#0 i8_fu_90 = 4'd0;
#0 sineIdx9_fu_94 = 9'd0;
#0 indvars_iv710_fu_98 = 9'd0;
#0 sineIdx_115_fu_102 = 9'd0;
#0 add_ln4617_fu_106 = 4'd0;
#0 add_ln46_118_fu_110 = 9'd0;
#0 add_ln46_219_fu_114 = 9'd0;
#0 phaseInc_load411_fu_118 = 32'd0;
#0 accumulators_load112_fu_122 = 32'd0;
#0 conv_i_i114_fu_126 = 32'd0;
#0 ap_done_reg = 1'b0;
end

MultiSineStream_accumulators_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
accumulators_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(accumulators_addr_reg_549_pp0_iter1_reg),
    .ce0(accumulators_ce0_local),
    .we0(accumulators_we0_local),
    .d0(add_ln49_fu_455_p2),
    .address1(accumulators_address1),
    .ce1(accumulators_ce1_local),
    .q1(accumulators_q1)
);

MultiSineStream_sine_lut_ROM_AUTO_1R #(
    .DataWidth( 24 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
sine_lut_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(sine_lut_address0),
    .ce0(sine_lut_ce0_local),
    .q0(sine_lut_q0)
);

MultiSineStream_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .phaseInc_address0(phaseInc_address0),
    .phaseInc_ce0(phaseInc_ce0_local),
    .phaseInc_q0(phaseInc_q0),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

MultiSineStream_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(1'b1)
);

MultiSineStream_regslice_both #(
    .DataWidth( 24 ))
regslice_both_samples_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(sine_lut_q0),
    .vld_in(samples_TVALID_int_regslice),
    .ack_in(samples_TREADY_int_regslice),
    .data_out(samples_TDATA),
    .vld_out(regslice_both_samples_U_vld_out),
    .ack_out(samples_TREADY),
    .apdone_blk(regslice_both_samples_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_152)) begin
        add_ln4617_fu_106 <= add_ln46_fu_337_p2;
    end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_152)) begin
    add_ln46_118_fu_110 <= add_ln46_1_fu_343_p2;
end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_152)) begin
    add_ln46_219_fu_114 <= add_ln46_2_fu_349_p2;
end
end

always @ (posedge ap_clk) begin
if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b0))) begin
    ap_loop_exit_ready_pp0_iter5_reg <= 1'b0;
end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
    ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_165)) begin
    if ((or_ln48_reg_545 == 1'd1)) begin
        ap_phi_reg_pp0_iter2_accumulators_load3_reg_202 <= accumulators_q1;
    end else if ((1'b1 == 1'b1)) begin
        ap_phi_reg_pp0_iter2_accumulators_load3_reg_202 <= ap_phi_reg_pp0_iter1_accumulators_load3_reg_202;
    end
end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_152)) begin
    i8_fu_90 <= i_fu_278_p3;
end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_152)) begin
    indvar_flatten7_fu_86 <= add_ln46_3_fu_308_p2;
end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_152)) begin
    indvars_iv710_fu_98 <= select_ln46_2_fu_294_p3;
end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_152)) begin
    sineIdx9_fu_94 <= sineIdx_fu_286_p3;
end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_152)) begin
    sineIdx_115_fu_102 <= sineIdx_1_fu_325_p2;
end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        accumulators_addr_reg_549 <= zext_ln46_fu_302_p1;
        accumulators_addr_reg_549_pp0_iter1_reg <= accumulators_addr_reg_549;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln46_reg_565 <= icmp_ln46_fu_355_p2;
        icmp_ln49_reg_560_pp0_iter1_reg <= icmp_ln49_reg_560;
        or_ln48_reg_545 <= or_ln48_fu_272_p2;
        or_ln48_reg_545_pp0_iter1_reg <= or_ln48_reg_545;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln48_reg_545 == 1'd1))) begin
        accumulators_load112_fu_122 <= accumulators_q1;
        phaseInc_load411_fu_118 <= phaseInc_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        address_reg_574 <= {{add_ln51_fu_439_p2[31:20]}};
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_accumulators_load3_reg_202 <= ap_phi_reg_pp0_iter0_accumulators_load3_reg_202;
        icmp_ln49_reg_560 <= icmp_ln49_fu_331_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        conv_i_i114_fu_126 <= add_ln51_fu_439_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        accumulators_ce0_local = 1'b1;
    end else begin
        accumulators_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        accumulators_ce1_local = 1'b1;
    end else begin
        accumulators_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln49_reg_560_pp0_iter1_reg == 1'd1))) begin
        accumulators_we0_local = 1'b1;
    end else begin
        accumulators_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln46_fu_355_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((or_ln48_reg_545_pp0_iter1_reg == 1'd0)) begin
        ap_phi_mux_accumulators_load3_phi_fu_205_p4 = conv_i_i114_fu_126;
    end else begin
        ap_phi_mux_accumulators_load3_phi_fu_205_p4 = ap_phi_reg_pp0_iter2_accumulators_load3_reg_202;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_452)) begin
            ap_phi_mux_first_iter_013_phi_fu_194_p4 = 1'd0;
        end else if ((ap_loop_init == 1'b1)) begin
            ap_phi_mux_first_iter_013_phi_fu_194_p4 = 1'd1;
        end else begin
            ap_phi_mux_first_iter_013_phi_fu_194_p4 = 1'd0;
        end
    end else begin
        ap_phi_mux_first_iter_013_phi_fu_194_p4 = 1'd0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_452)) begin
            ap_phi_mux_icmp_ln4916_phi_fu_184_p4 = icmp_ln49_reg_560;
        end else if ((ap_loop_init == 1'b1)) begin
            ap_phi_mux_icmp_ln4916_phi_fu_184_p4 = 1'd0;
        end else begin
            ap_phi_mux_icmp_ln4916_phi_fu_184_p4 = icmp_ln49_reg_560;
        end
    end else begin
        ap_phi_mux_icmp_ln4916_phi_fu_184_p4 = icmp_ln49_reg_560;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_add_ln4617_load = 4'd1;
    end else begin
        ap_sig_allocacmp_add_ln4617_load = add_ln4617_fu_106;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_add_ln46_118_load = 9'd96;
    end else begin
        ap_sig_allocacmp_add_ln46_118_load = add_ln46_118_fu_110;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_add_ln46_219_load = 9'd48;
    end else begin
        ap_sig_allocacmp_add_ln46_219_load = add_ln46_219_fu_114;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i8_load = 4'd0;
    end else begin
        ap_sig_allocacmp_i8_load = i8_fu_90;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten7_load = 9'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten7_load = indvar_flatten7_fu_86;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvars_iv710_load = 9'd48;
    end else begin
        ap_sig_allocacmp_indvars_iv710_load = indvars_iv710_fu_98;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_sineIdx9_load = 9'd0;
    end else begin
        ap_sig_allocacmp_sineIdx9_load = sineIdx9_fu_94;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_sineIdx_115_load = 9'd0;
    end else begin
        ap_sig_allocacmp_sineIdx_115_load = sineIdx_115_fu_102;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        phaseInc_ce0_local = 1'b1;
    end else begin
        phaseInc_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1)))) begin
        samples_TDATA_blk_n = samples_TREADY_int_regslice;
    end else begin
        samples_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        samples_TVALID_int_regslice = 1'b1;
    end else begin
        samples_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        sine_lut_ce0_local = 1'b1;
    end else begin
        sine_lut_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign accumulators_address1 = zext_ln46_fu_302_p1;

assign add_ln46_1_fu_343_p2 = (select_ln46_2_fu_294_p3 + 9'd48);

assign add_ln46_2_fu_349_p2 = (sineIdx_fu_286_p3 + 9'd48);

assign add_ln46_3_fu_308_p2 = (ap_sig_allocacmp_indvar_flatten7_load + 9'd1);

assign add_ln46_fu_337_p2 = (i_fu_278_p3 + 4'd1);

assign add_ln49_fu_455_p2 = (accumulators_load112_fu_122 + sub_ln49_fu_433_p2);

assign add_ln51_fu_439_p2 = (phaseInc_load411_fu_118 + ap_phi_mux_accumulators_load3_phi_fu_205_p4);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_loop_exit_ready_pp0_iter5_reg == 1'b1) & (regslice_both_samples_U_apdone_blk == 1'b1)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_block_state6_pp0_stage0_iter5)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_loop_exit_ready_pp0_iter5_reg == 1'b1) & (regslice_both_samples_U_apdone_blk == 1'b1)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_block_state6_pp0_stage0_iter5)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp0 = ((ap_loop_exit_ready_pp0_iter5_reg == 1'b1) & (regslice_both_samples_U_apdone_blk == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_loop_exit_ready_pp0_iter5_reg == 1'b1) & (regslice_both_samples_U_apdone_blk == 1'b1)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_block_state6_pp0_stage0_iter5)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp0 = ((ap_loop_exit_ready_pp0_iter5_reg == 1'b1) & (regslice_both_samples_U_apdone_blk == 1'b1));
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter4 = (samples_TREADY_int_regslice == 1'b0);
end

always @ (*) begin
    ap_block_state6_pp0_stage0_iter5 = ((regslice_both_samples_U_apdone_blk == 1'b1) | (samples_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_condition_152 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_165 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_452 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln46_reg_565 == 1'd0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_accumulators_load3_reg_202 = 'bx;

assign ap_ready = ap_ready_sig;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign i_fu_278_p3 = ((ap_phi_mux_icmp_ln4916_phi_fu_184_p4[0:0] == 1'b1) ? ap_sig_allocacmp_add_ln4617_load : ap_sig_allocacmp_i8_load);

assign icmp_ln46_fu_355_p2 = ((ap_sig_allocacmp_indvar_flatten7_load == 9'd383) ? 1'b1 : 1'b0);

assign icmp_ln49_fu_331_p2 = ((sineIdx_1_fu_325_p2 == select_ln46_2_fu_294_p3) ? 1'b1 : 1'b0);

assign or_ln48_fu_272_p2 = (ap_phi_mux_icmp_ln4916_phi_fu_184_p4 | ap_phi_mux_first_iter_013_phi_fu_194_p4);

assign phaseInc_address0 = zext_ln46_fu_302_p1;

assign samples_TVALID = regslice_both_samples_U_vld_out;

assign select_ln46_2_fu_294_p3 = ((ap_phi_mux_icmp_ln4916_phi_fu_184_p4[0:0] == 1'b1) ? ap_sig_allocacmp_add_ln46_118_load : ap_sig_allocacmp_indvars_iv710_load);

assign select_ln48_fu_317_p3 = ((ap_phi_mux_icmp_ln4916_phi_fu_184_p4[0:0] == 1'b1) ? ap_sig_allocacmp_add_ln46_219_load : ap_sig_allocacmp_sineIdx_115_load);

assign shl_ln49_1_fu_427_p2 = phaseInc_load411_fu_118 << 32'd4;

assign shl_ln49_fu_421_p2 = phaseInc_load411_fu_118 << 32'd6;

assign sineIdx_1_fu_325_p2 = (select_ln48_fu_317_p3 + 9'd1);

assign sineIdx_fu_286_p3 = ((ap_phi_mux_icmp_ln4916_phi_fu_184_p4[0:0] == 1'b1) ? ap_sig_allocacmp_add_ln46_219_load : ap_sig_allocacmp_sineIdx9_load);

assign sine_lut_address0 = zext_ln54_fu_467_p1;

assign sub_ln49_fu_433_p2 = (shl_ln49_fu_421_p2 - shl_ln49_1_fu_427_p2);

assign zext_ln46_fu_302_p1 = i_fu_278_p3;

assign zext_ln54_fu_467_p1 = address_reg_574;


reg find_kernel_block = 0;
// synthesis translate_off
`include "MultiSineStream_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //MultiSineStream

