-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity SimpleSineStream is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 6;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    samples_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
    samples_TVALID : OUT STD_LOGIC;
    samples_TREADY : IN STD_LOGIC;
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of SimpleSineStream is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "SimpleSineStream_SimpleSineStream,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.505000,HLS_SYN_LAT=53,HLS_SYN_TPT=none,HLS_SYN_MEM=6,HLS_SYN_DSP=0,HLS_SYN_FF=286,HLS_SYN_LUT=449,HLS_VERSION=2024_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal accumulator_i : STD_LOGIC_VECTOR (31 downto 0);
    signal accumulator_o : STD_LOGIC_VECTOR (31 downto 0);
    signal accumulator_o_ap_vld : STD_LOGIC;
    signal phaseInc : STD_LOGIC_VECTOR (31 downto 0);
    signal phaseInc_read_reg_106 : STD_LOGIC_VECTOR (31 downto 0);
    signal accumulator_read_reg_111 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_SimpleSineStream_Pipeline_VITIS_LOOP_38_1_fu_69_ap_start : STD_LOGIC;
    signal grp_SimpleSineStream_Pipeline_VITIS_LOOP_38_1_fu_69_ap_done : STD_LOGIC;
    signal grp_SimpleSineStream_Pipeline_VITIS_LOOP_38_1_fu_69_ap_idle : STD_LOGIC;
    signal grp_SimpleSineStream_Pipeline_VITIS_LOOP_38_1_fu_69_ap_ready : STD_LOGIC;
    signal grp_SimpleSineStream_Pipeline_VITIS_LOOP_38_1_fu_69_samples_TREADY : STD_LOGIC;
    signal grp_SimpleSineStream_Pipeline_VITIS_LOOP_38_1_fu_69_samples_TDATA : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_SimpleSineStream_Pipeline_VITIS_LOOP_38_1_fu_69_samples_TVALID : STD_LOGIC;
    signal grp_SimpleSineStream_Pipeline_VITIS_LOOP_38_1_fu_69_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal samples_TDATA_reg : STD_LOGIC_VECTOR (23 downto 0);
    signal shl_ln38_fu_81_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln38_1_fu_87_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln38_fu_93_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal regslice_both_samples_U_apdone_blk : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal samples_TDATA_int_regslice : STD_LOGIC_VECTOR (23 downto 0);
    signal samples_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_samples_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component SimpleSineStream_SimpleSineStream_Pipeline_VITIS_LOOP_38_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        samples_TREADY : IN STD_LOGIC;
        accumulator_load : IN STD_LOGIC_VECTOR (31 downto 0);
        phaseInc : IN STD_LOGIC_VECTOR (31 downto 0);
        samples_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
        samples_TVALID : OUT STD_LOGIC );
    end component;


    component SimpleSineStream_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        accumulator_o : IN STD_LOGIC_VECTOR (31 downto 0);
        accumulator_o_ap_vld : IN STD_LOGIC;
        accumulator_i : OUT STD_LOGIC_VECTOR (31 downto 0);
        phaseInc : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component SimpleSineStream_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    grp_SimpleSineStream_Pipeline_VITIS_LOOP_38_1_fu_69 : component SimpleSineStream_SimpleSineStream_Pipeline_VITIS_LOOP_38_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_SimpleSineStream_Pipeline_VITIS_LOOP_38_1_fu_69_ap_start,
        ap_done => grp_SimpleSineStream_Pipeline_VITIS_LOOP_38_1_fu_69_ap_done,
        ap_idle => grp_SimpleSineStream_Pipeline_VITIS_LOOP_38_1_fu_69_ap_idle,
        ap_ready => grp_SimpleSineStream_Pipeline_VITIS_LOOP_38_1_fu_69_ap_ready,
        samples_TREADY => grp_SimpleSineStream_Pipeline_VITIS_LOOP_38_1_fu_69_samples_TREADY,
        accumulator_load => accumulator_read_reg_111,
        phaseInc => phaseInc_read_reg_106,
        samples_TDATA => grp_SimpleSineStream_Pipeline_VITIS_LOOP_38_1_fu_69_samples_TDATA,
        samples_TVALID => grp_SimpleSineStream_Pipeline_VITIS_LOOP_38_1_fu_69_samples_TVALID);

    control_s_axi_U : component SimpleSineStream_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        accumulator_o => accumulator_o,
        accumulator_o_ap_vld => accumulator_o_ap_vld,
        accumulator_i => accumulator_i,
        phaseInc => phaseInc,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    regslice_both_samples_U : component SimpleSineStream_regslice_both
    generic map (
        DataWidth => 24)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => samples_TDATA_int_regslice,
        vld_in => grp_SimpleSineStream_Pipeline_VITIS_LOOP_38_1_fu_69_samples_TVALID,
        ack_in => samples_TREADY_int_regslice,
        data_out => samples_TDATA,
        vld_out => regslice_both_samples_U_vld_out,
        ack_out => samples_TREADY,
        apdone_blk => regslice_both_samples_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_SimpleSineStream_Pipeline_VITIS_LOOP_38_1_fu_69_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_SimpleSineStream_Pipeline_VITIS_LOOP_38_1_fu_69_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_SimpleSineStream_Pipeline_VITIS_LOOP_38_1_fu_69_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_SimpleSineStream_Pipeline_VITIS_LOOP_38_1_fu_69_ap_ready = ap_const_logic_1)) then 
                    grp_SimpleSineStream_Pipeline_VITIS_LOOP_38_1_fu_69_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                accumulator_read_reg_111 <= accumulator_i;
                phaseInc_read_reg_106 <= phaseInc;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_SimpleSineStream_Pipeline_VITIS_LOOP_38_1_fu_69_samples_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                samples_TDATA_reg <= grp_SimpleSineStream_Pipeline_VITIS_LOOP_38_1_fu_69_samples_TDATA;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_SimpleSineStream_Pipeline_VITIS_LOOP_38_1_fu_69_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state3, regslice_both_samples_U_apdone_blk)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_SimpleSineStream_Pipeline_VITIS_LOOP_38_1_fu_69_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (regslice_both_samples_U_apdone_blk = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    accumulator_o <= std_logic_vector(unsigned(accumulator_i) + unsigned(sub_ln38_fu_93_p2));

    accumulator_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            accumulator_o_ap_vld <= ap_const_logic_1;
        else 
            accumulator_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_SimpleSineStream_Pipeline_VITIS_LOOP_38_1_fu_69_ap_done)
    begin
        if ((grp_SimpleSineStream_Pipeline_VITIS_LOOP_38_1_fu_69_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state3_blk_assign_proc : process(regslice_both_samples_U_apdone_blk)
    begin
        if ((regslice_both_samples_U_apdone_blk = ap_const_logic_1)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state3, regslice_both_samples_U_apdone_blk)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (regslice_both_samples_U_apdone_blk = ap_const_logic_0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state3, regslice_both_samples_U_apdone_blk)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (regslice_both_samples_U_apdone_blk = ap_const_logic_0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    grp_SimpleSineStream_Pipeline_VITIS_LOOP_38_1_fu_69_ap_start <= grp_SimpleSineStream_Pipeline_VITIS_LOOP_38_1_fu_69_ap_start_reg;
    grp_SimpleSineStream_Pipeline_VITIS_LOOP_38_1_fu_69_samples_TREADY <= (samples_TREADY_int_regslice and ap_CS_fsm_state2);

    samples_TDATA_int_regslice_assign_proc : process(grp_SimpleSineStream_Pipeline_VITIS_LOOP_38_1_fu_69_samples_TDATA, grp_SimpleSineStream_Pipeline_VITIS_LOOP_38_1_fu_69_samples_TVALID, ap_CS_fsm_state2, samples_TDATA_reg)
    begin
        if (((grp_SimpleSineStream_Pipeline_VITIS_LOOP_38_1_fu_69_samples_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            samples_TDATA_int_regslice <= grp_SimpleSineStream_Pipeline_VITIS_LOOP_38_1_fu_69_samples_TDATA;
        else 
            samples_TDATA_int_regslice <= samples_TDATA_reg;
        end if; 
    end process;

    samples_TVALID <= regslice_both_samples_U_vld_out;
    shl_ln38_1_fu_87_p2 <= std_logic_vector(shift_left(unsigned(phaseInc),to_integer(unsigned('0' & ap_const_lv32_4(31-1 downto 0)))));
    shl_ln38_fu_81_p2 <= std_logic_vector(shift_left(unsigned(phaseInc),to_integer(unsigned('0' & ap_const_lv32_6(31-1 downto 0)))));
    sub_ln38_fu_93_p2 <= std_logic_vector(unsigned(shl_ln38_fu_81_p2) - unsigned(shl_ln38_1_fu_87_p2));
end behav;
