-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity MultiSineStreamBidirectional is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    phaseInc_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    phaseInc_TVALID : IN STD_LOGIC;
    phaseInc_TREADY : OUT STD_LOGIC;
    samples_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
    samples_TVALID : OUT STD_LOGIC;
    samples_TREADY : IN STD_LOGIC );
end;


architecture behav of MultiSineStreamBidirectional is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "MultiSineStreamBidirectional_MultiSineStreamBidirectional,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.931750,HLS_SYN_LAT=402,HLS_SYN_TPT=none,HLS_SYN_MEM=6,HLS_SYN_DSP=0,HLS_SYN_FF=347,HLS_SYN_LUT=531,HLS_VERSION=2024_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv9_30 : STD_LOGIC_VECTOR (8 downto 0) := "000110000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv9_180 : STD_LOGIC_VECTOR (8 downto 0) := "110000000";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";

    signal ap_rst_n_inv : STD_LOGIC;
    signal phaseIncsLocal_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal phaseIncsLocal_ce0 : STD_LOGIC;
    signal phaseIncsLocal_we0 : STD_LOGIC;
    signal phaseIncsLocal_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal accumulators_address1 : STD_LOGIC_VECTOR (2 downto 0);
    signal accumulators_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sine_lut_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal sine_lut_q0 : STD_LOGIC_VECTOR (23 downto 0);
    signal samples_TDATA_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal first_iter_0_reg_157 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_fu_206_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_reg_462 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln45_reg_462_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_reg_462_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln47_fu_241_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln47_reg_466 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal select_ln45_2_fu_289_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln45_2_reg_470 : STD_LOGIC_VECTOR (8 downto 0);
    signal accumulators_addr_reg_475 : STD_LOGIC_VECTOR (2 downto 0);
    signal accumulators_addr_reg_475_pp0_iter2_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln53_fu_303_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln53_reg_486 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln48_1_fu_344_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln48_1_reg_491 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_ap_done : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_flush_enable : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_condition_pp0_exit_iter1_state5 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_ap_start : STD_LOGIC;
    signal grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_ap_idle : STD_LOGIC;
    signal grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_ap_ready : STD_LOGIC;
    signal grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_phaseInc_TREADY : STD_LOGIC;
    signal grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_phaseIncsLocal_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_phaseIncsLocal_ce0 : STD_LOGIC;
    signal grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_phaseIncsLocal_we0 : STD_LOGIC;
    signal grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_phaseIncsLocal_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_first_iter_0_phi_fu_162_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal zext_ln45_fu_297_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln53_fu_391_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sineIdx_1_fu_74 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal indvars_iv9_fu_78 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal sineIdx_fu_82 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal select_ln45_1_fu_275_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal i_1_fu_86 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal select_ln45_fu_267_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal indvar_flatten_fu_90 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal add_ln45_fu_212_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal conv_i_i1_fu_94 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal add_ln50_fu_375_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal accumulators_load1_fu_98 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal phaseIncsLocal_load4_fu_102 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal phaseIncsLocal_ce0_local : STD_LOGIC;
    signal accumulators_ce1_local : STD_LOGIC;
    signal accumulators_we0_local : STD_LOGIC;
    signal add_ln48_fu_396_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal accumulators_ce0_local : STD_LOGIC;
    signal sine_lut_ce0_local : STD_LOGIC;
    signal icmp_ln48_fu_235_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln45_1_fu_247_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln45_2_fu_261_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln45_3_fu_283_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln47_fu_253_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln48_fu_357_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln48_1_fu_363_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal address_fu_381_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln48_fu_369_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal regslice_both_samples_U_apdone_blk : STD_LOGIC;
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal regslice_both_phaseInc_U_apdone_blk : STD_LOGIC;
    signal phaseInc_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal phaseInc_TVALID_int_regslice : STD_LOGIC;
    signal phaseInc_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_phaseInc_U_ack_in : STD_LOGIC;
    signal samples_TVALID_int_regslice : STD_LOGIC;
    signal samples_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_samples_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component MultiSineStreamBidirectional_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        phaseInc_TVALID : IN STD_LOGIC;
        phaseInc_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        phaseInc_TREADY : OUT STD_LOGIC;
        phaseIncsLocal_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        phaseIncsLocal_ce0 : OUT STD_LOGIC;
        phaseIncsLocal_we0 : OUT STD_LOGIC;
        phaseIncsLocal_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component MultiSineStreamBidirectional_phaseIncsLocal_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component MultiSineStreamBidirectional_accumulators_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component MultiSineStreamBidirectional_sine_lut_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (11 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;


    component MultiSineStreamBidirectional_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    phaseIncsLocal_U : component MultiSineStreamBidirectional_phaseIncsLocal_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => phaseIncsLocal_address0,
        ce0 => phaseIncsLocal_ce0,
        we0 => phaseIncsLocal_we0,
        d0 => grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_phaseIncsLocal_d0,
        q0 => phaseIncsLocal_q0);

    accumulators_U : component MultiSineStreamBidirectional_accumulators_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => accumulators_addr_reg_475_pp0_iter2_reg,
        ce0 => accumulators_ce0_local,
        we0 => accumulators_we0_local,
        d0 => add_ln48_fu_396_p2,
        address1 => accumulators_address1,
        ce1 => accumulators_ce1_local,
        q1 => accumulators_q1);

    sine_lut_U : component MultiSineStreamBidirectional_sine_lut_ROM_AUTO_1R
    generic map (
        DataWidth => 24,
        AddressRange => 4096,
        AddressWidth => 12)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => sine_lut_address0,
        ce0 => sine_lut_ce0_local,
        q0 => sine_lut_q0);

    grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170 : component MultiSineStreamBidirectional_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_ap_start,
        ap_done => grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_ap_done,
        ap_idle => grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_ap_idle,
        ap_ready => grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_ap_ready,
        phaseInc_TVALID => phaseInc_TVALID_int_regslice,
        phaseInc_TDATA => phaseInc_TDATA_int_regslice,
        phaseInc_TREADY => grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_phaseInc_TREADY,
        phaseIncsLocal_address0 => grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_phaseIncsLocal_address0,
        phaseIncsLocal_ce0 => grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_phaseIncsLocal_ce0,
        phaseIncsLocal_we0 => grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_phaseIncsLocal_we0,
        phaseIncsLocal_d0 => grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_phaseIncsLocal_d0);

    regslice_both_phaseInc_U : component MultiSineStreamBidirectional_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => phaseInc_TDATA,
        vld_in => phaseInc_TVALID,
        ack_in => regslice_both_phaseInc_U_ack_in,
        data_out => phaseInc_TDATA_int_regslice,
        vld_out => phaseInc_TVALID_int_regslice,
        ack_out => phaseInc_TREADY_int_regslice,
        apdone_blk => regslice_both_phaseInc_U_apdone_blk);

    regslice_both_samples_U : component MultiSineStreamBidirectional_regslice_both
    generic map (
        DataWidth => 24)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => sine_lut_q0,
        vld_in => samples_TVALID_int_regslice,
        ack_in => samples_TREADY_int_regslice,
        data_out => samples_TDATA,
        vld_out => regslice_both_samples_U_vld_out,
        ack_out => samples_TREADY,
        apdone_blk => regslice_both_samples_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_pp0_flush_enable)) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_ap_done = ap_const_logic_1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter1_state5)) then 
                        ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter0;
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_ap_done = ap_const_logic_1))) then 
                    ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_ap_ready = ap_const_logic_1)) then 
                    grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    conv_i_i1_fu_94_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((or_ln47_reg_466 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    conv_i_i1_fu_94 <= accumulators_q1;
                elsif (((icmp_ln45_reg_462_pp0_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
                    conv_i_i1_fu_94 <= add_ln50_fu_375_p2;
                end if;
            end if; 
        end if;
    end process;

    first_iter_0_reg_157_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_ap_done = ap_const_logic_1))) then 
                first_iter_0_reg_157 <= ap_const_lv1_1;
            elsif (((icmp_ln45_reg_462_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                first_iter_0_reg_157 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    i_1_fu_86_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
                i_1_fu_86 <= ap_const_lv4_0;
            elsif (((icmp_ln45_reg_462 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                i_1_fu_86 <= select_ln45_fu_267_p3;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_90_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
                indvar_flatten_fu_90 <= ap_const_lv9_0;
            elsif (((icmp_ln45_fu_206_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                indvar_flatten_fu_90 <= add_ln45_fu_212_p2;
            end if; 
        end if;
    end process;

    indvars_iv9_fu_78_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
                indvars_iv9_fu_78 <= ap_const_lv9_30;
            elsif (((icmp_ln45_reg_462 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                indvars_iv9_fu_78 <= select_ln45_2_fu_289_p3;
            end if; 
        end if;
    end process;

    sineIdx_1_fu_74_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
                sineIdx_1_fu_74 <= ap_const_lv9_0;
            elsif (((icmp_ln45_reg_462 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                sineIdx_1_fu_74 <= add_ln53_fu_303_p2;
            end if; 
        end if;
    end process;

    sineIdx_fu_82_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
                sineIdx_fu_82 <= ap_const_lv9_0;
            elsif (((icmp_ln45_reg_462 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                sineIdx_fu_82 <= select_ln45_1_fu_275_p3;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                accumulators_addr_reg_475 <= zext_ln45_fu_297_p1(3 - 1 downto 0);
                add_ln53_reg_486 <= add_ln53_fu_303_p2;
                or_ln47_reg_466 <= or_ln47_fu_241_p2;
                select_ln45_2_reg_470 <= select_ln45_2_fu_289_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                accumulators_addr_reg_475_pp0_iter2_reg <= accumulators_addr_reg_475;
                icmp_ln48_1_reg_491 <= icmp_ln48_1_fu_344_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((or_ln47_reg_466 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                accumulators_load1_fu_98 <= accumulators_q1;
                phaseIncsLocal_load4_fu_102 <= phaseIncsLocal_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln45_reg_462 <= icmp_ln45_fu_206_p2;
                icmp_ln45_reg_462_pp0_iter1_reg <= icmp_ln45_reg_462;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                icmp_ln45_reg_462_pp0_iter2_reg <= icmp_ln45_reg_462_pp0_iter1_reg;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_CS_fsm, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_state3, grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_ap_done, ap_block_pp0_stage0_subdone, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, regslice_both_samples_U_apdone_blk, ap_CS_fsm_state10)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) and not(((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0)))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state10 => 
                if (((regslice_both_samples_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    accumulators_address1 <= zext_ln45_fu_297_p1(3 - 1 downto 0);

    accumulators_ce0_local_assign_proc : process(ap_block_pp0_stage0_11001_grp1, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            accumulators_ce0_local <= ap_const_logic_1;
        else 
            accumulators_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    accumulators_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001_grp1, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            accumulators_ce1_local <= ap_const_logic_1;
        else 
            accumulators_ce1_local <= ap_const_logic_0;
        end if; 
    end process;


    accumulators_we0_local_assign_proc : process(ap_block_pp0_stage0_11001_grp1, icmp_ln48_1_reg_491, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (icmp_ln48_1_reg_491 = ap_const_lv1_1))) then 
            accumulators_we0_local <= ap_const_logic_1;
        else 
            accumulators_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    add_ln45_1_fu_247_p2 <= std_logic_vector(unsigned(sineIdx_fu_82) + unsigned(ap_const_lv9_30));
    add_ln45_2_fu_261_p2 <= std_logic_vector(unsigned(i_1_fu_86) + unsigned(ap_const_lv4_1));
    add_ln45_3_fu_283_p2 <= std_logic_vector(unsigned(indvars_iv9_fu_78) + unsigned(ap_const_lv9_30));
    add_ln45_fu_212_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_90) + unsigned(ap_const_lv9_1));
    add_ln48_fu_396_p2 <= std_logic_vector(unsigned(accumulators_load1_fu_98) + unsigned(sub_ln48_fu_369_p2));
    add_ln50_fu_375_p2 <= std_logic_vector(unsigned(phaseIncsLocal_load4_fu_102) + unsigned(conv_i_i1_fu_94));
    add_ln53_fu_303_p2 <= std_logic_vector(unsigned(select_ln47_fu_253_p3) + unsigned(ap_const_lv9_1));
    address_fu_381_p4 <= add_ln50_fu_375_p2(31 downto 20);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(3);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(4);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state10_blk_assign_proc : process(regslice_both_samples_U_apdone_blk)
    begin
        if ((regslice_both_samples_U_apdone_blk = ap_const_logic_1)) then 
            ap_ST_fsm_state10_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state10_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state1_blk <= ap_const_logic_0;
    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_ap_done)
    begin
        if ((grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_grp1_assign_proc : process(ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, samples_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_01001_grp1 <= (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (samples_TREADY_int_regslice = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (samples_TREADY_int_regslice = ap_const_logic_0)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, samples_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (samples_TREADY_int_regslice = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (samples_TREADY_int_regslice = ap_const_logic_0)));
    end process;


    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, samples_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_11001_grp1 <= (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (samples_TREADY_int_regslice = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (samples_TREADY_int_regslice = ap_const_logic_0)));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, samples_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (samples_TREADY_int_regslice = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (samples_TREADY_int_regslice = ap_const_logic_0)));
    end process;


    ap_condition_pp0_exit_iter1_state5_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_condition_pp0_exit_iter1_state5 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter1_state5 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_pp0_flush_enable_assign_proc : process(icmp_ln45_fu_206_p2, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone)
    begin
        if (((icmp_ln45_fu_206_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_pp0_flush_enable <= ap_const_logic_1;
        else 
            ap_condition_pp0_flush_enable <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_first_iter_0_phi_fu_162_p4_assign_proc : process(first_iter_0_reg_157, icmp_ln45_reg_462_pp0_iter1_reg, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0)
    begin
        if (((icmp_ln45_reg_462_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            ap_phi_mux_first_iter_0_phi_fu_162_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_first_iter_0_phi_fu_162_p4 <= first_iter_0_reg_157;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_ap_start <= grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_ap_start_reg;
    icmp_ln45_fu_206_p2 <= "1" when (indvar_flatten_fu_90 = ap_const_lv9_180) else "0";
    icmp_ln48_1_fu_344_p2 <= "1" when (add_ln53_reg_486 = select_ln45_2_reg_470) else "0";
    icmp_ln48_fu_235_p2 <= "1" when (sineIdx_1_fu_74 = indvars_iv9_fu_78) else "0";
    or_ln47_fu_241_p2 <= (icmp_ln48_fu_235_p2 or ap_phi_mux_first_iter_0_phi_fu_162_p4);
    phaseInc_TREADY <= regslice_both_phaseInc_U_ack_in;

    phaseInc_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_state3, grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_phaseInc_TREADY)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            phaseInc_TREADY_int_regslice <= grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_phaseInc_TREADY;
        else 
            phaseInc_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    phaseIncsLocal_address0_assign_proc : process(ap_CS_fsm_state3, grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_phaseIncsLocal_address0, zext_ln45_fu_297_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            phaseIncsLocal_address0 <= grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_phaseIncsLocal_address0;
        else 
            phaseIncsLocal_address0 <= zext_ln45_fu_297_p1(3 - 1 downto 0);
        end if; 
    end process;


    phaseIncsLocal_ce0_assign_proc : process(ap_CS_fsm_state3, grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_phaseIncsLocal_ce0, phaseIncsLocal_ce0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            phaseIncsLocal_ce0 <= grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_phaseIncsLocal_ce0;
        else 
            phaseIncsLocal_ce0 <= phaseIncsLocal_ce0_local;
        end if; 
    end process;


    phaseIncsLocal_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001_grp1, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            phaseIncsLocal_ce0_local <= ap_const_logic_1;
        else 
            phaseIncsLocal_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    phaseIncsLocal_we0_assign_proc : process(ap_CS_fsm_state3, grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_phaseIncsLocal_we0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            phaseIncsLocal_we0 <= grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_phaseIncsLocal_we0;
        else 
            phaseIncsLocal_we0 <= ap_const_logic_0;
        end if; 
    end process;


    samples_TDATA_blk_n_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_grp1, ap_enable_reg_pp0_iter5, samples_TREADY_int_regslice)
    begin
        if ((((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)))) then 
            samples_TDATA_blk_n <= samples_TREADY_int_regslice;
        else 
            samples_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    samples_TVALID <= regslice_both_samples_U_vld_out;

    samples_TVALID_int_regslice_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            samples_TVALID_int_regslice <= ap_const_logic_1;
        else 
            samples_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    select_ln45_1_fu_275_p3 <= 
        add_ln45_1_fu_247_p2 when (icmp_ln48_fu_235_p2(0) = '1') else 
        sineIdx_fu_82;
    select_ln45_2_fu_289_p3 <= 
        add_ln45_3_fu_283_p2 when (icmp_ln48_fu_235_p2(0) = '1') else 
        indvars_iv9_fu_78;
    select_ln45_fu_267_p3 <= 
        add_ln45_2_fu_261_p2 when (icmp_ln48_fu_235_p2(0) = '1') else 
        i_1_fu_86;
    select_ln47_fu_253_p3 <= 
        add_ln45_1_fu_247_p2 when (icmp_ln48_fu_235_p2(0) = '1') else 
        sineIdx_1_fu_74;
    shl_ln48_1_fu_363_p2 <= std_logic_vector(shift_left(unsigned(phaseIncsLocal_load4_fu_102),to_integer(unsigned('0' & ap_const_lv32_4(31-1 downto 0)))));
    shl_ln48_fu_357_p2 <= std_logic_vector(shift_left(unsigned(phaseIncsLocal_load4_fu_102),to_integer(unsigned('0' & ap_const_lv32_6(31-1 downto 0)))));
    sine_lut_address0 <= zext_ln53_fu_391_p1(12 - 1 downto 0);

    sine_lut_ce0_local_assign_proc : process(ap_block_pp0_stage0_11001_grp1, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            sine_lut_ce0_local <= ap_const_logic_1;
        else 
            sine_lut_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    sub_ln48_fu_369_p2 <= std_logic_vector(unsigned(shl_ln48_fu_357_p2) - unsigned(shl_ln48_1_fu_363_p2));
    zext_ln45_fu_297_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln45_fu_267_p3),64));
    zext_ln53_fu_391_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(address_fu_381_p4),64));
end behav;
