
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2024.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2025 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xmultisine.h"

/*
* The configuration table for devices
*/

XMultisine_Config XMultisine_ConfigTable[XPAR_XMULTISINE_NUM_INSTANCES] =
{
	{
		XPAR_AUDIO_COMPONENTS_MULTISINE_0_DEVICE_ID,
		XPAR_AUDIO_COMPONENTS_MULTISINE_0_S_AXI_BUS_A_BASEADDR
	}
};


