// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="SimpleSine_SimpleSine,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.514000,HLS_SYN_LAT=53,HLS_SYN_TPT=none,HLS_SYN_MEM=8,HLS_SYN_DSP=0,HLS_SYN_FF=355,HLS_SYN_LUT=493,HLS_VERSION=2024_2}" *)

module SimpleSine (
        ap_clk,
        ap_rst_n,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 9;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] accumulator_i;
wire   [31:0] accumulator_o;
reg    accumulator_o_ap_vld;
wire   [31:0] phaseInc;
reg   [31:0] phaseInc_read_reg_116;
reg   [31:0] accumulator_read_reg_121;
wire    grp_SimpleSine_Pipeline_VITIS_LOOP_45_1_fu_79_ap_start;
wire    grp_SimpleSine_Pipeline_VITIS_LOOP_45_1_fu_79_ap_done;
wire    grp_SimpleSine_Pipeline_VITIS_LOOP_45_1_fu_79_ap_idle;
wire    grp_SimpleSine_Pipeline_VITIS_LOOP_45_1_fu_79_ap_ready;
wire   [5:0] grp_SimpleSine_Pipeline_VITIS_LOOP_45_1_fu_79_samples_address0;
wire    grp_SimpleSine_Pipeline_VITIS_LOOP_45_1_fu_79_samples_ce0;
wire    grp_SimpleSine_Pipeline_VITIS_LOOP_45_1_fu_79_samples_we0;
wire   [23:0] grp_SimpleSine_Pipeline_VITIS_LOOP_45_1_fu_79_samples_d0;
reg    grp_SimpleSine_Pipeline_VITIS_LOOP_45_1_fu_79_ap_start_reg;
wire    ap_CS_fsm_state2;
wire   [31:0] shl_ln45_fu_91_p2;
wire   [31:0] shl_ln45_1_fu_97_p2;
wire   [31:0] sub_ln45_fu_103_p2;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 grp_SimpleSine_Pipeline_VITIS_LOOP_45_1_fu_79_ap_start_reg = 1'b0;
end

SimpleSine_SimpleSine_Pipeline_VITIS_LOOP_45_1 grp_SimpleSine_Pipeline_VITIS_LOOP_45_1_fu_79(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_SimpleSine_Pipeline_VITIS_LOOP_45_1_fu_79_ap_start),
    .ap_done(grp_SimpleSine_Pipeline_VITIS_LOOP_45_1_fu_79_ap_done),
    .ap_idle(grp_SimpleSine_Pipeline_VITIS_LOOP_45_1_fu_79_ap_idle),
    .ap_ready(grp_SimpleSine_Pipeline_VITIS_LOOP_45_1_fu_79_ap_ready),
    .accumulator_load(accumulator_read_reg_121),
    .phaseInc(phaseInc_read_reg_116),
    .samples_address0(grp_SimpleSine_Pipeline_VITIS_LOOP_45_1_fu_79_samples_address0),
    .samples_ce0(grp_SimpleSine_Pipeline_VITIS_LOOP_45_1_fu_79_samples_ce0),
    .samples_we0(grp_SimpleSine_Pipeline_VITIS_LOOP_45_1_fu_79_samples_we0),
    .samples_d0(grp_SimpleSine_Pipeline_VITIS_LOOP_45_1_fu_79_samples_d0)
);

SimpleSine_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .accumulator_o(accumulator_o),
    .accumulator_o_ap_vld(accumulator_o_ap_vld),
    .accumulator_i(accumulator_i),
    .phaseInc(phaseInc),
    .samples_address0(grp_SimpleSine_Pipeline_VITIS_LOOP_45_1_fu_79_samples_address0),
    .samples_ce0(grp_SimpleSine_Pipeline_VITIS_LOOP_45_1_fu_79_samples_ce0),
    .samples_we0(grp_SimpleSine_Pipeline_VITIS_LOOP_45_1_fu_79_samples_we0),
    .samples_d0(grp_SimpleSine_Pipeline_VITIS_LOOP_45_1_fu_79_samples_d0),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_SimpleSine_Pipeline_VITIS_LOOP_45_1_fu_79_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_SimpleSine_Pipeline_VITIS_LOOP_45_1_fu_79_ap_start_reg <= 1'b1;
        end else if ((grp_SimpleSine_Pipeline_VITIS_LOOP_45_1_fu_79_ap_ready == 1'b1)) begin
            grp_SimpleSine_Pipeline_VITIS_LOOP_45_1_fu_79_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        accumulator_read_reg_121 <= accumulator_i;
        phaseInc_read_reg_116 <= phaseInc;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        accumulator_o_ap_vld = 1'b1;
    end else begin
        accumulator_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_SimpleSine_Pipeline_VITIS_LOOP_45_1_fu_79_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_SimpleSine_Pipeline_VITIS_LOOP_45_1_fu_79_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_SimpleSine_Pipeline_VITIS_LOOP_45_1_fu_79_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_SimpleSine_Pipeline_VITIS_LOOP_45_1_fu_79_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign accumulator_o = (accumulator_i + sub_ln45_fu_103_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_SimpleSine_Pipeline_VITIS_LOOP_45_1_fu_79_ap_start = grp_SimpleSine_Pipeline_VITIS_LOOP_45_1_fu_79_ap_start_reg;

assign shl_ln45_1_fu_97_p2 = phaseInc << 32'd4;

assign shl_ln45_fu_91_p2 = phaseInc << 32'd6;

assign sub_ln45_fu_103_p2 = (shl_ln45_fu_91_p2 - shl_ln45_1_fu_97_p2);

endmodule //SimpleSine
