// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="MultiSineStreamBidirectional_MultiSineStreamBidirectional,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.931750,HLS_SYN_LAT=402,HLS_SYN_TPT=none,HLS_SYN_MEM=6,HLS_SYN_DSP=0,HLS_SYN_FF=347,HLS_SYN_LUT=531,HLS_VERSION=2024_2}" *)

module MultiSineStreamBidirectional (
        ap_clk,
        ap_rst_n,
        phaseInc_TDATA,
        phaseInc_TVALID,
        phaseInc_TREADY,
        samples_TDATA,
        samples_TVALID,
        samples_TREADY
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_pp0_stage0 = 5'd8;
parameter    ap_ST_fsm_state10 = 5'd16;

input   ap_clk;
input   ap_rst_n;
input  [31:0] phaseInc_TDATA;
input   phaseInc_TVALID;
output   phaseInc_TREADY;
output  [23:0] samples_TDATA;
output   samples_TVALID;
input   samples_TREADY;

 reg    ap_rst_n_inv;
reg   [2:0] phaseIncsLocal_address0;
reg    phaseIncsLocal_ce0;
reg    phaseIncsLocal_we0;
wire   [31:0] phaseIncsLocal_q0;
wire   [2:0] accumulators_address1;
wire   [31:0] accumulators_q1;
wire   [11:0] sine_lut_address0;
wire   [23:0] sine_lut_q0;
reg    samples_TDATA_blk_n;
reg    ap_enable_reg_pp0_iter4;
wire    ap_block_pp0_stage0_grp1;
reg    ap_enable_reg_pp0_iter5;
reg   [0:0] first_iter_0_reg_157;
wire   [0:0] icmp_ln45_fu_206_p2;
reg   [0:0] icmp_ln45_reg_462;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln45_reg_462_pp0_iter1_reg;
reg   [0:0] icmp_ln45_reg_462_pp0_iter2_reg;
wire   [0:0] or_ln47_fu_241_p2;
reg   [0:0] or_ln47_reg_466;
reg    ap_block_pp0_stage0_11001_grp1;
wire   [8:0] select_ln45_2_fu_289_p3;
reg   [8:0] select_ln45_2_reg_470;
reg   [2:0] accumulators_addr_reg_475;
reg   [2:0] accumulators_addr_reg_475_pp0_iter2_reg;
wire   [8:0] add_ln53_fu_303_p2;
reg   [8:0] add_ln53_reg_486;
wire   [0:0] icmp_ln48_1_fu_344_p2;
reg   [0:0] icmp_ln48_1_reg_491;
reg    ap_enable_reg_pp0_iter0;
wire    ap_CS_fsm_state3;
wire    grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_ap_done;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_flush_enable;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_condition_pp0_exit_iter1_state5;
reg    ap_enable_reg_pp0_iter3;
wire    grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_ap_start;
wire    grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_ap_idle;
wire    grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_ap_ready;
wire    grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_phaseInc_TREADY;
wire   [2:0] grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_phaseIncsLocal_address0;
wire    grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_phaseIncsLocal_ce0;
wire    grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_phaseIncsLocal_we0;
wire   [31:0] grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_phaseIncsLocal_d0;
reg   [0:0] ap_phi_mux_first_iter_0_phi_fu_162_p4;
wire    ap_block_pp0_stage0;
reg    grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_ap_start_reg;
wire    ap_CS_fsm_state2;
wire   [63:0] zext_ln45_fu_297_p1;
wire   [63:0] zext_ln53_fu_391_p1;
reg   [8:0] sineIdx_1_fu_74;
wire    ap_CS_fsm_state1;
reg   [8:0] indvars_iv9_fu_78;
reg   [8:0] sineIdx_fu_82;
wire   [8:0] select_ln45_1_fu_275_p3;
reg   [3:0] i_1_fu_86;
wire   [3:0] select_ln45_fu_267_p3;
reg   [8:0] indvar_flatten_fu_90;
wire   [8:0] add_ln45_fu_212_p2;
reg   [31:0] conv_i_i1_fu_94;
wire   [31:0] add_ln50_fu_375_p2;
reg   [31:0] accumulators_load1_fu_98;
reg   [31:0] phaseIncsLocal_load4_fu_102;
reg    ap_block_pp0_stage0_01001_grp1;
reg    phaseIncsLocal_ce0_local;
reg    accumulators_ce1_local;
reg    accumulators_we0_local;
wire   [31:0] add_ln48_fu_396_p2;
reg    accumulators_ce0_local;
reg    sine_lut_ce0_local;
wire   [0:0] icmp_ln48_fu_235_p2;
wire   [8:0] add_ln45_1_fu_247_p2;
wire   [3:0] add_ln45_2_fu_261_p2;
wire   [8:0] add_ln45_3_fu_283_p2;
wire   [8:0] select_ln47_fu_253_p3;
wire   [31:0] shl_ln48_fu_357_p2;
wire   [31:0] shl_ln48_1_fu_363_p2;
wire   [11:0] address_fu_381_p4;
wire   [31:0] sub_ln48_fu_369_p2;
reg   [4:0] ap_NS_fsm;
wire    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state10_blk;
wire    regslice_both_samples_U_apdone_blk;
wire    ap_CS_fsm_state10;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    regslice_both_phaseInc_U_apdone_blk;
wire   [31:0] phaseInc_TDATA_int_regslice;
wire    phaseInc_TVALID_int_regslice;
reg    phaseInc_TREADY_int_regslice;
wire    regslice_both_phaseInc_U_ack_in;
reg    samples_TVALID_int_regslice;
wire    samples_TREADY_int_regslice;
wire    regslice_both_samples_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_ap_start_reg = 1'b0;
#0 sineIdx_1_fu_74 = 9'd0;
#0 indvars_iv9_fu_78 = 9'd0;
#0 sineIdx_fu_82 = 9'd0;
#0 i_1_fu_86 = 4'd0;
#0 indvar_flatten_fu_90 = 9'd0;
#0 conv_i_i1_fu_94 = 32'd0;
#0 accumulators_load1_fu_98 = 32'd0;
#0 phaseIncsLocal_load4_fu_102 = 32'd0;
end

MultiSineStreamBidirectional_phaseIncsLocal_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
phaseIncsLocal_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(phaseIncsLocal_address0),
    .ce0(phaseIncsLocal_ce0),
    .we0(phaseIncsLocal_we0),
    .d0(grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_phaseIncsLocal_d0),
    .q0(phaseIncsLocal_q0)
);

MultiSineStreamBidirectional_accumulators_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
accumulators_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(accumulators_addr_reg_475_pp0_iter2_reg),
    .ce0(accumulators_ce0_local),
    .we0(accumulators_we0_local),
    .d0(add_ln48_fu_396_p2),
    .address1(accumulators_address1),
    .ce1(accumulators_ce1_local),
    .q1(accumulators_q1)
);

MultiSineStreamBidirectional_sine_lut_ROM_AUTO_1R #(
    .DataWidth( 24 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
sine_lut_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(sine_lut_address0),
    .ce0(sine_lut_ce0_local),
    .q0(sine_lut_q0)
);

MultiSineStreamBidirectional_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1 grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_ap_start),
    .ap_done(grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_ap_done),
    .ap_idle(grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_ap_idle),
    .ap_ready(grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_ap_ready),
    .phaseInc_TVALID(phaseInc_TVALID_int_regslice),
    .phaseInc_TDATA(phaseInc_TDATA_int_regslice),
    .phaseInc_TREADY(grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_phaseInc_TREADY),
    .phaseIncsLocal_address0(grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_phaseIncsLocal_address0),
    .phaseIncsLocal_ce0(grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_phaseIncsLocal_ce0),
    .phaseIncsLocal_we0(grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_phaseIncsLocal_we0),
    .phaseIncsLocal_d0(grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_phaseIncsLocal_d0)
);

MultiSineStreamBidirectional_regslice_both #(
    .DataWidth( 32 ))
regslice_both_phaseInc_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(phaseInc_TDATA),
    .vld_in(phaseInc_TVALID),
    .ack_in(regslice_both_phaseInc_U_ack_in),
    .data_out(phaseInc_TDATA_int_regslice),
    .vld_out(phaseInc_TVALID_int_regslice),
    .ack_out(phaseInc_TREADY_int_regslice),
    .apdone_blk(regslice_both_phaseInc_U_apdone_blk)
);

MultiSineStreamBidirectional_regslice_both #(
    .DataWidth( 24 ))
regslice_both_samples_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(sine_lut_q0),
    .vld_in(samples_TVALID_int_regslice),
    .ack_in(samples_TREADY_int_regslice),
    .data_out(samples_TDATA),
    .vld_out(regslice_both_samples_U_vld_out),
    .ack_out(samples_TREADY),
    .apdone_blk(regslice_both_samples_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp0_flush_enable)) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state3) & (grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_ap_done == 1'b1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter1_state5)) begin
                ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter0;
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end else if (((1'b1 == ap_CS_fsm_state3) & (grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_ap_done == 1'b1))) begin
            ap_enable_reg_pp0_iter5 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_ap_start_reg <= 1'b1;
        end else if ((grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_ap_ready == 1'b1)) begin
            grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((or_ln47_reg_466 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            conv_i_i1_fu_94 <= accumulators_q1;
        end else if (((icmp_ln45_reg_462_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            conv_i_i1_fu_94 <= add_ln50_fu_375_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_ap_done == 1'b1))) begin
        first_iter_0_reg_157 <= 1'd1;
    end else if (((icmp_ln45_reg_462_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        first_iter_0_reg_157 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        i_1_fu_86 <= 4'd0;
    end else if (((icmp_ln45_reg_462 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        i_1_fu_86 <= select_ln45_fu_267_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        indvar_flatten_fu_90 <= 9'd0;
    end else if (((icmp_ln45_fu_206_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        indvar_flatten_fu_90 <= add_ln45_fu_212_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        indvars_iv9_fu_78 <= 9'd48;
    end else if (((icmp_ln45_reg_462 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        indvars_iv9_fu_78 <= select_ln45_2_fu_289_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        sineIdx_1_fu_74 <= 9'd0;
    end else if (((icmp_ln45_reg_462 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        sineIdx_1_fu_74 <= add_ln53_fu_303_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        sineIdx_fu_82 <= 9'd0;
    end else if (((icmp_ln45_reg_462 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        sineIdx_fu_82 <= select_ln45_1_fu_275_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        accumulators_addr_reg_475 <= zext_ln45_fu_297_p1;
        add_ln53_reg_486 <= add_ln53_fu_303_p2;
        or_ln47_reg_466 <= or_ln47_fu_241_p2;
        select_ln45_2_reg_470 <= select_ln45_2_fu_289_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        accumulators_addr_reg_475_pp0_iter2_reg <= accumulators_addr_reg_475;
        icmp_ln48_1_reg_491 <= icmp_ln48_1_fu_344_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((or_ln47_reg_466 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        accumulators_load1_fu_98 <= accumulators_q1;
        phaseIncsLocal_load4_fu_102 <= phaseIncsLocal_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln45_reg_462 <= icmp_ln45_fu_206_p2;
        icmp_ln45_reg_462_pp0_iter1_reg <= icmp_ln45_reg_462;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icmp_ln45_reg_462_pp0_iter2_reg <= icmp_ln45_reg_462_pp0_iter1_reg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        accumulators_ce0_local = 1'b1;
    end else begin
        accumulators_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        accumulators_ce1_local = 1'b1;
    end else begin
        accumulators_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln48_1_reg_491 == 1'd1))) begin
        accumulators_we0_local = 1'b1;
    end else begin
        accumulators_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_samples_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

assign ap_ST_fsm_state1_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_condition_pp0_exit_iter1_state5 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter1_state5 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln45_fu_206_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_pp0_flush_enable = 1'b1;
    end else begin
        ap_condition_pp0_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln45_reg_462_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_mux_first_iter_0_phi_fu_162_p4 = 1'd0;
    end else begin
        ap_phi_mux_first_iter_0_phi_fu_162_p4 = first_iter_0_reg_157;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        phaseInc_TREADY_int_regslice = grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_phaseInc_TREADY;
    end else begin
        phaseInc_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        phaseIncsLocal_address0 = grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_phaseIncsLocal_address0;
    end else begin
        phaseIncsLocal_address0 = zext_ln45_fu_297_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        phaseIncsLocal_ce0 = grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_phaseIncsLocal_ce0;
    end else begin
        phaseIncsLocal_ce0 = phaseIncsLocal_ce0_local;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        phaseIncsLocal_ce0_local = 1'b1;
    end else begin
        phaseIncsLocal_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        phaseIncsLocal_we0 = grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_phaseIncsLocal_we0;
    end else begin
        phaseIncsLocal_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1)) | ((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter4 == 1'b1)))) begin
        samples_TDATA_blk_n = samples_TREADY_int_regslice;
    end else begin
        samples_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        samples_TVALID_int_regslice = 1'b1;
    end else begin
        samples_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        sine_lut_ce0_local = 1'b1;
    end else begin
        sine_lut_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b0)) & ~((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b0)) | ((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((regslice_both_samples_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign accumulators_address1 = zext_ln45_fu_297_p1;

assign add_ln45_1_fu_247_p2 = (sineIdx_fu_82 + 9'd48);

assign add_ln45_2_fu_261_p2 = (i_1_fu_86 + 4'd1);

assign add_ln45_3_fu_283_p2 = (indvars_iv9_fu_78 + 9'd48);

assign add_ln45_fu_212_p2 = (indvar_flatten_fu_90 + 9'd1);

assign add_ln48_fu_396_p2 = (accumulators_load1_fu_98 + sub_ln48_fu_369_p2);

assign add_ln50_fu_375_p2 = (phaseIncsLocal_load4_fu_102 + conv_i_i1_fu_94);

assign add_ln53_fu_303_p2 = (select_ln47_fu_253_p3 + 9'd1);

assign address_fu_381_p4 = {{add_ln50_fu_375_p2[31:20]}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = (((ap_enable_reg_pp0_iter5 == 1'b1) & (samples_TREADY_int_regslice == 1'b0)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (samples_TREADY_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter5 == 1'b1) & (samples_TREADY_int_regslice == 1'b0)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (samples_TREADY_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = (((ap_enable_reg_pp0_iter5 == 1'b1) & (samples_TREADY_int_regslice == 1'b0)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (samples_TREADY_int_regslice == 1'b0)));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter5 == 1'b1) & (samples_TREADY_int_regslice == 1'b0)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (samples_TREADY_int_regslice == 1'b0)));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_ap_start = grp_MultiSineStreamBidirectional_Pipeline_VITIS_LOOP_39_1_fu_170_ap_start_reg;

assign icmp_ln45_fu_206_p2 = ((indvar_flatten_fu_90 == 9'd384) ? 1'b1 : 1'b0);

assign icmp_ln48_1_fu_344_p2 = ((add_ln53_reg_486 == select_ln45_2_reg_470) ? 1'b1 : 1'b0);

assign icmp_ln48_fu_235_p2 = ((sineIdx_1_fu_74 == indvars_iv9_fu_78) ? 1'b1 : 1'b0);

assign or_ln47_fu_241_p2 = (icmp_ln48_fu_235_p2 | ap_phi_mux_first_iter_0_phi_fu_162_p4);

assign phaseInc_TREADY = regslice_both_phaseInc_U_ack_in;

assign samples_TVALID = regslice_both_samples_U_vld_out;

assign select_ln45_1_fu_275_p3 = ((icmp_ln48_fu_235_p2[0:0] == 1'b1) ? add_ln45_1_fu_247_p2 : sineIdx_fu_82);

assign select_ln45_2_fu_289_p3 = ((icmp_ln48_fu_235_p2[0:0] == 1'b1) ? add_ln45_3_fu_283_p2 : indvars_iv9_fu_78);

assign select_ln45_fu_267_p3 = ((icmp_ln48_fu_235_p2[0:0] == 1'b1) ? add_ln45_2_fu_261_p2 : i_1_fu_86);

assign select_ln47_fu_253_p3 = ((icmp_ln48_fu_235_p2[0:0] == 1'b1) ? add_ln45_1_fu_247_p2 : sineIdx_1_fu_74);

assign shl_ln48_1_fu_363_p2 = phaseIncsLocal_load4_fu_102 << 32'd4;

assign shl_ln48_fu_357_p2 = phaseIncsLocal_load4_fu_102 << 32'd6;

assign sine_lut_address0 = zext_ln53_fu_391_p1;

assign sub_ln48_fu_369_p2 = (shl_ln48_fu_357_p2 - shl_ln48_1_fu_363_p2);

assign zext_ln45_fu_297_p1 = select_ln45_fu_267_p3;

assign zext_ln53_fu_391_p1 = address_fu_381_p4;

endmodule //MultiSineStreamBidirectional
