// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="MultiSineMaster_MultiSineMaster,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=403,HLS_SYN_TPT=none,HLS_SYN_MEM=10,HLS_SYN_DSP=0,HLS_SYN_FF=1899,HLS_SYN_LUT=1468,HLS_VERSION=2024_2}" *)

module MultiSineMaster (
        ap_clk,
        ap_rst_n,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 32;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
wire    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_idle_pp0;
wire    ap_ready;
reg    gmem_0_AWVALID;
wire    gmem_0_AWREADY;
reg    gmem_0_WVALID;
wire    gmem_0_WREADY;
wire   [31:0] gmem_0_WDATA;
reg    gmem_0_ARVALID;
wire    gmem_0_ARREADY;
wire    gmem_0_RVALID;
reg    gmem_0_RREADY;
wire   [31:0] gmem_0_RDATA;
wire   [8:0] gmem_0_RFIFONUM;
wire    gmem_0_BVALID;
reg    gmem_0_BREADY;
reg   [0:0] first_iter_0_reg_220;
reg    ap_block_state2_io;
reg   [0:0] or_ln49_reg_657;
reg    ap_block_state10_pp0_stage0_iter9;
reg   [0:0] first_iter_0_reg_220_pp0_iter11_reg;
reg    ap_block_state13_io;
reg   [0:0] icmp_ln47_reg_647;
reg   [0:0] icmp_ln47_reg_647_pp0_iter17_reg;
reg    ap_block_state19_pp0_stage0_iter18;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln47_fu_304_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    ap_condition_exit_pp0_iter0_stage0_pp0_iter1_reg;
reg    ap_block_pp0_stage0_11001;
reg    ap_condition_exit_pp0_iter0_stage0_pp0_iter2_reg;
reg    ap_condition_exit_pp0_iter0_stage0_pp0_iter3_reg;
reg    ap_condition_exit_pp0_iter0_stage0_pp0_iter4_reg;
reg    ap_condition_exit_pp0_iter0_stage0_pp0_iter5_reg;
reg    ap_condition_exit_pp0_iter0_stage0_pp0_iter6_reg;
reg    ap_condition_exit_pp0_iter0_stage0_pp0_iter7_reg;
reg    ap_condition_exit_pp0_iter0_stage0_pp0_iter8_reg;
reg    ap_loop_exit_ready_delayed;
wire   [31:0] phaseInc;
wire   [31:0] samples;
wire   [2:0] accumulators_address1;
wire   [31:0] accumulators_q1;
wire   [11:0] sine_lut_address0;
wire   [23:0] sine_lut_q0;
reg    gmem_blk_n_AW;
wire    ap_block_pp0_stage0;
reg    gmem_blk_n_W;
reg    gmem_blk_n_B;
reg    gmem_blk_n_AR;
reg    gmem_blk_n_R;
reg   [0:0] first_iter_0_reg_220_pp0_iter1_reg;
reg   [0:0] first_iter_0_reg_220_pp0_iter2_reg;
reg   [0:0] first_iter_0_reg_220_pp0_iter3_reg;
reg   [0:0] first_iter_0_reg_220_pp0_iter4_reg;
reg   [0:0] first_iter_0_reg_220_pp0_iter5_reg;
reg   [0:0] first_iter_0_reg_220_pp0_iter6_reg;
reg   [0:0] first_iter_0_reg_220_pp0_iter7_reg;
reg   [0:0] first_iter_0_reg_220_pp0_iter8_reg;
reg   [0:0] first_iter_0_reg_220_pp0_iter9_reg;
reg   [0:0] first_iter_0_reg_220_pp0_iter10_reg;
wire    ap_block_pp0_stage0_11001_grp0;
wire    ap_block_pp0_stage0_subdone_grp0;
reg   [31:0] samples_read_reg_637;
reg   [31:0] samples_read_reg_637_pp0_iter1_reg;
reg   [31:0] samples_read_reg_637_pp0_iter2_reg;
reg   [31:0] samples_read_reg_637_pp0_iter3_reg;
reg   [31:0] samples_read_reg_637_pp0_iter4_reg;
reg   [31:0] samples_read_reg_637_pp0_iter5_reg;
reg   [31:0] samples_read_reg_637_pp0_iter6_reg;
reg   [31:0] samples_read_reg_637_pp0_iter7_reg;
reg   [31:0] samples_read_reg_637_pp0_iter8_reg;
reg   [31:0] samples_read_reg_637_pp0_iter9_reg;
reg   [31:0] samples_read_reg_637_pp0_iter10_reg;
reg   [31:0] samples_read_reg_637_pp0_iter11_reg;
reg   [31:0] phaseInc_read_reg_642;
reg   [0:0] icmp_ln47_reg_647_pp0_iter1_reg;
reg   [0:0] icmp_ln47_reg_647_pp0_iter2_reg;
reg   [0:0] icmp_ln47_reg_647_pp0_iter3_reg;
reg   [0:0] icmp_ln47_reg_647_pp0_iter4_reg;
reg   [0:0] icmp_ln47_reg_647_pp0_iter5_reg;
reg   [0:0] icmp_ln47_reg_647_pp0_iter6_reg;
reg   [0:0] icmp_ln47_reg_647_pp0_iter7_reg;
reg   [0:0] icmp_ln47_reg_647_pp0_iter8_reg;
reg   [0:0] icmp_ln47_reg_647_pp0_iter9_reg;
reg   [0:0] icmp_ln47_reg_647_pp0_iter10_reg;
reg   [0:0] icmp_ln47_reg_647_pp0_iter11_reg;
reg   [0:0] icmp_ln47_reg_647_pp0_iter12_reg;
reg   [0:0] icmp_ln47_reg_647_pp0_iter13_reg;
reg   [0:0] icmp_ln47_reg_647_pp0_iter14_reg;
reg   [0:0] icmp_ln47_reg_647_pp0_iter15_reg;
reg   [0:0] icmp_ln47_reg_647_pp0_iter16_reg;
wire   [0:0] or_ln49_fu_356_p2;
reg   [0:0] or_ln49_reg_657_pp0_iter9_reg;
reg   [2:0] accumulators_addr_reg_661;
reg   [2:0] accumulators_addr_reg_661_pp0_iter9_reg;
wire   [0:0] icmp_ln50_fu_409_p2;
reg   [0:0] icmp_ln50_reg_667;
reg   [0:0] icmp_ln50_reg_667_pp0_iter9_reg;
reg   [11:0] address_reg_677;
reg   [23:0] sine_lut_load_reg_693;
wire    ap_loop_init;
reg   [0:0] ap_phi_mux_icmp_ln5015_phi_fu_236_p4;
reg    ap_loop_init_pp0_iter1_reg;
reg    ap_loop_init_pp0_iter2_reg;
reg    ap_loop_init_pp0_iter3_reg;
reg    ap_loop_init_pp0_iter4_reg;
reg    ap_loop_init_pp0_iter5_reg;
reg    ap_loop_init_pp0_iter6_reg;
reg    ap_loop_init_pp0_iter7_reg;
reg    ap_loop_init_pp0_iter8_reg;
reg   [31:0] ap_phi_mux_accumulators_load3_phi_fu_246_p4;
reg   [31:0] ap_phi_reg_pp0_iter10_accumulators_load3_reg_243;
wire   [31:0] ap_phi_reg_pp0_iter0_accumulators_load3_reg_243;
reg   [31:0] ap_phi_reg_pp0_iter1_accumulators_load3_reg_243;
reg   [31:0] ap_phi_reg_pp0_iter2_accumulators_load3_reg_243;
reg   [31:0] ap_phi_reg_pp0_iter3_accumulators_load3_reg_243;
reg   [31:0] ap_phi_reg_pp0_iter4_accumulators_load3_reg_243;
reg   [31:0] ap_phi_reg_pp0_iter5_accumulators_load3_reg_243;
reg   [31:0] ap_phi_reg_pp0_iter6_accumulators_load3_reg_243;
reg   [31:0] ap_phi_reg_pp0_iter7_accumulators_load3_reg_243;
reg   [31:0] ap_phi_reg_pp0_iter8_accumulators_load3_reg_243;
reg   [31:0] ap_phi_reg_pp0_iter9_accumulators_load3_reg_243;
wire   [31:0] i_cast_cast_fu_390_p1;
wire   [31:0] zext_ln54_fu_534_p1;
wire   [31:0] sext_ln47_1_fu_324_p1;
wire   [31:0] sext_ln47_fu_547_p1;
reg    ap_block_pp0_stage0_01001;
reg   [8:0] indvar_flatten7_fu_106;
wire   [8:0] add_ln47_2_fu_295_p2;
reg   [8:0] ap_sig_allocacmp_indvar_flatten7_load;
reg   [8:0] ap_sig_allocacmp_indvar_flatten7_load_1;
reg   [3:0] i8_fu_110;
wire   [3:0] i_fu_362_p3;
reg   [8:0] sineIdx9_fu_114;
wire   [8:0] sineIdx_fu_370_p3;
reg   [8:0] indvars_iv710_fu_118;
wire   [8:0] select_ln47_2_fu_378_p3;
reg   [8:0] sineIdx_114_fu_122;
wire   [8:0] sineIdx_2_fu_403_p2;
reg   [3:0] add_ln4716_fu_126;
wire   [3:0] add_ln47_fu_415_p2;
reg   [8:0] add_ln47_117_fu_130;
wire   [8:0] add_ln47_1_fu_421_p2;
reg   [8:0] add_ln5218_fu_134;
wire   [8:0] add_ln52_fu_427_p2;
reg   [31:0] gmem_addr_1_read411_fu_138;
reg   [31:0] accumulators_load112_fu_142;
reg   [31:0] empty_fu_146;
wire   [31:0] add_ln52_1_fu_488_p2;
reg    accumulators_ce1_local;
reg    accumulators_we0_local;
wire   [31:0] add_ln50_fu_522_p2;
reg    accumulators_ce0_local;
reg    sine_lut_ce0_local;
wire   [29:0] trunc_ln47_1_fu_315_p4;
wire   [2:0] empty_19_fu_386_p1;
wire   [8:0] select_ln49_fu_395_p3;
wire   [31:0] shl_ln50_fu_504_p2;
wire   [31:0] shl_ln50_1_fu_510_p2;
wire   [31:0] sub_ln50_fu_516_p2;
wire   [29:0] trunc_ln_fu_538_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_649;
reg    ap_condition_889;
reg    ap_condition_598;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 indvar_flatten7_fu_106 = 9'd0;
#0 i8_fu_110 = 4'd0;
#0 sineIdx9_fu_114 = 9'd0;
#0 indvars_iv710_fu_118 = 9'd0;
#0 sineIdx_114_fu_122 = 9'd0;
#0 add_ln4716_fu_126 = 4'd0;
#0 add_ln47_117_fu_130 = 9'd0;
#0 add_ln5218_fu_134 = 9'd0;
#0 gmem_addr_1_read411_fu_138 = 32'd0;
#0 accumulators_load112_fu_142 = 32'd0;
#0 empty_fu_146 = 32'd0;
#0 ap_done_reg = 1'b0;
end

MultiSineMaster_accumulators_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
accumulators_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(accumulators_addr_reg_661_pp0_iter9_reg),
    .ce0(accumulators_ce0_local),
    .we0(accumulators_we0_local),
    .d0(add_ln50_fu_522_p2),
    .address1(accumulators_address1),
    .ce1(accumulators_ce1_local),
    .q1(accumulators_q1)
);

MultiSineMaster_sine_lut_ROM_AUTO_1R #(
    .DataWidth( 24 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
sine_lut_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(sine_lut_address0),
    .ce0(sine_lut_ce0_local),
    .q0(sine_lut_q0)
);

MultiSineMaster_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .phaseInc(phaseInc),
    .samples(samples),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

MultiSineMaster_gmem_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 32 ),
    .CH0_USER_AW( 32 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(gmem_0_ARVALID),
    .I_CH0_ARREADY(gmem_0_ARREADY),
    .I_CH0_ARADDR(sext_ln47_1_fu_324_p1),
    .I_CH0_ARLEN(32'd8),
    .I_CH0_RVALID(gmem_0_RVALID),
    .I_CH0_RREADY(gmem_0_RREADY),
    .I_CH0_RDATA(gmem_0_RDATA),
    .I_CH0_RFIFONUM(gmem_0_RFIFONUM),
    .I_CH0_AWVALID(gmem_0_AWVALID),
    .I_CH0_AWREADY(gmem_0_AWREADY),
    .I_CH0_AWADDR(sext_ln47_fu_547_p1),
    .I_CH0_AWLEN(32'd384),
    .I_CH0_WVALID(gmem_0_WVALID),
    .I_CH0_WREADY(gmem_0_WREADY),
    .I_CH0_WDATA(gmem_0_WDATA),
    .I_CH0_WSTRB(4'd7),
    .I_CH0_BVALID(gmem_0_BVALID),
    .I_CH0_BREADY(gmem_0_BREADY)
);

MultiSineMaster_flow_control_loop_delay_pipe flow_control_loop_delay_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(1'b1),
    .ap_loop_exit_ready_delayed(ap_loop_exit_ready_delayed)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter18_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if ((1'b1 == ap_condition_649)) begin
            add_ln4716_fu_126 <= 4'd1;
        end else if ((ap_enable_reg_pp0_iter8 == 1'b1)) begin
            add_ln4716_fu_126 <= add_ln47_fu_415_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if ((1'b1 == ap_condition_649)) begin
            add_ln47_117_fu_130 <= 9'd96;
        end else if ((ap_enable_reg_pp0_iter8 == 1'b1)) begin
            add_ln47_117_fu_130 <= add_ln47_1_fu_421_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if ((1'b1 == ap_condition_649)) begin
            add_ln5218_fu_134 <= 9'd48;
        end else if ((ap_enable_reg_pp0_iter8 == 1'b1)) begin
            add_ln5218_fu_134 <= add_ln52_fu_427_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_exit_ready_pp0_iter17_reg == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_loop_exit_ready_pp0_iter18_reg <= 1'b0;
    end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((or_ln49_reg_657 == 1'd1)) begin
            ap_phi_reg_pp0_iter10_accumulators_load3_reg_243 <= accumulators_q1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter10_accumulators_load3_reg_243 <= ap_phi_reg_pp0_iter9_accumulators_load3_reg_243;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_889)) begin
            first_iter_0_reg_220 <= 1'd0;
        end else if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            first_iter_0_reg_220 <= 1'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if ((1'b1 == ap_condition_649)) begin
            i8_fu_110 <= 4'd0;
        end else if ((ap_enable_reg_pp0_iter8 == 1'b1)) begin
            i8_fu_110 <= i_fu_362_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_598)) begin
        indvar_flatten7_fu_106 <= add_ln47_2_fu_295_p2;
    end
end

always @ (posedge ap_clk) begin
if ((1'b0 == ap_block_pp0_stage0_11001)) begin
    if ((1'b1 == ap_condition_649)) begin
        indvars_iv710_fu_118 <= 9'd48;
    end else if ((ap_enable_reg_pp0_iter8 == 1'b1)) begin
        indvars_iv710_fu_118 <= select_ln47_2_fu_378_p3;
    end
end
end

always @ (posedge ap_clk) begin
if ((1'b0 == ap_block_pp0_stage0_11001)) begin
    if ((1'b1 == ap_condition_649)) begin
        sineIdx9_fu_114 <= 9'd0;
    end else if ((ap_enable_reg_pp0_iter8 == 1'b1)) begin
        sineIdx9_fu_114 <= sineIdx_fu_370_p3;
    end
end
end

always @ (posedge ap_clk) begin
if ((1'b0 == ap_block_pp0_stage0_11001)) begin
    if ((1'b1 == ap_condition_649)) begin
        sineIdx_114_fu_122 <= 9'd0;
    end else if ((ap_enable_reg_pp0_iter8 == 1'b1)) begin
        sineIdx_114_fu_122 <= sineIdx_2_fu_403_p2;
    end
end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        accumulators_addr_reg_661 <= i_cast_cast_fu_390_p1;
        accumulators_addr_reg_661_pp0_iter9_reg <= accumulators_addr_reg_661;
        address_reg_677 <= {{add_ln52_1_fu_488_p2[31:20]}};
        ap_condition_exit_pp0_iter0_stage0_pp0_iter3_reg <= ap_condition_exit_pp0_iter0_stage0_pp0_iter2_reg;
        ap_condition_exit_pp0_iter0_stage0_pp0_iter4_reg <= ap_condition_exit_pp0_iter0_stage0_pp0_iter3_reg;
        ap_condition_exit_pp0_iter0_stage0_pp0_iter5_reg <= ap_condition_exit_pp0_iter0_stage0_pp0_iter4_reg;
        ap_condition_exit_pp0_iter0_stage0_pp0_iter6_reg <= ap_condition_exit_pp0_iter0_stage0_pp0_iter5_reg;
        ap_condition_exit_pp0_iter0_stage0_pp0_iter7_reg <= ap_condition_exit_pp0_iter0_stage0_pp0_iter6_reg;
        ap_condition_exit_pp0_iter0_stage0_pp0_iter8_reg <= ap_condition_exit_pp0_iter0_stage0_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        ap_loop_init_pp0_iter3_reg <= ap_loop_init_pp0_iter2_reg;
        ap_loop_init_pp0_iter4_reg <= ap_loop_init_pp0_iter3_reg;
        ap_loop_init_pp0_iter5_reg <= ap_loop_init_pp0_iter4_reg;
        ap_loop_init_pp0_iter6_reg <= ap_loop_init_pp0_iter5_reg;
        ap_loop_init_pp0_iter7_reg <= ap_loop_init_pp0_iter6_reg;
        ap_loop_init_pp0_iter8_reg <= ap_loop_init_pp0_iter7_reg;
        first_iter_0_reg_220_pp0_iter10_reg <= first_iter_0_reg_220_pp0_iter9_reg;
        first_iter_0_reg_220_pp0_iter11_reg <= first_iter_0_reg_220_pp0_iter10_reg;
        first_iter_0_reg_220_pp0_iter2_reg <= first_iter_0_reg_220_pp0_iter1_reg;
        first_iter_0_reg_220_pp0_iter3_reg <= first_iter_0_reg_220_pp0_iter2_reg;
        first_iter_0_reg_220_pp0_iter4_reg <= first_iter_0_reg_220_pp0_iter3_reg;
        first_iter_0_reg_220_pp0_iter5_reg <= first_iter_0_reg_220_pp0_iter4_reg;
        first_iter_0_reg_220_pp0_iter6_reg <= first_iter_0_reg_220_pp0_iter5_reg;
        first_iter_0_reg_220_pp0_iter7_reg <= first_iter_0_reg_220_pp0_iter6_reg;
        first_iter_0_reg_220_pp0_iter8_reg <= first_iter_0_reg_220_pp0_iter7_reg;
        first_iter_0_reg_220_pp0_iter9_reg <= first_iter_0_reg_220_pp0_iter8_reg;
        icmp_ln47_reg_647_pp0_iter10_reg <= icmp_ln47_reg_647_pp0_iter9_reg;
        icmp_ln47_reg_647_pp0_iter11_reg <= icmp_ln47_reg_647_pp0_iter10_reg;
        icmp_ln47_reg_647_pp0_iter12_reg <= icmp_ln47_reg_647_pp0_iter11_reg;
        icmp_ln47_reg_647_pp0_iter13_reg <= icmp_ln47_reg_647_pp0_iter12_reg;
        icmp_ln47_reg_647_pp0_iter14_reg <= icmp_ln47_reg_647_pp0_iter13_reg;
        icmp_ln47_reg_647_pp0_iter15_reg <= icmp_ln47_reg_647_pp0_iter14_reg;
        icmp_ln47_reg_647_pp0_iter16_reg <= icmp_ln47_reg_647_pp0_iter15_reg;
        icmp_ln47_reg_647_pp0_iter17_reg <= icmp_ln47_reg_647_pp0_iter16_reg;
        icmp_ln47_reg_647_pp0_iter2_reg <= icmp_ln47_reg_647_pp0_iter1_reg;
        icmp_ln47_reg_647_pp0_iter3_reg <= icmp_ln47_reg_647_pp0_iter2_reg;
        icmp_ln47_reg_647_pp0_iter4_reg <= icmp_ln47_reg_647_pp0_iter3_reg;
        icmp_ln47_reg_647_pp0_iter5_reg <= icmp_ln47_reg_647_pp0_iter4_reg;
        icmp_ln47_reg_647_pp0_iter6_reg <= icmp_ln47_reg_647_pp0_iter5_reg;
        icmp_ln47_reg_647_pp0_iter7_reg <= icmp_ln47_reg_647_pp0_iter6_reg;
        icmp_ln47_reg_647_pp0_iter8_reg <= icmp_ln47_reg_647_pp0_iter7_reg;
        icmp_ln47_reg_647_pp0_iter9_reg <= icmp_ln47_reg_647_pp0_iter8_reg;
        icmp_ln50_reg_667_pp0_iter9_reg <= icmp_ln50_reg_667;
        or_ln49_reg_657 <= or_ln49_fu_356_p2;
        or_ln49_reg_657_pp0_iter9_reg <= or_ln49_reg_657;
        samples_read_reg_637_pp0_iter10_reg <= samples_read_reg_637_pp0_iter9_reg;
        samples_read_reg_637_pp0_iter11_reg <= samples_read_reg_637_pp0_iter10_reg;
        samples_read_reg_637_pp0_iter2_reg <= samples_read_reg_637_pp0_iter1_reg;
        samples_read_reg_637_pp0_iter3_reg <= samples_read_reg_637_pp0_iter2_reg;
        samples_read_reg_637_pp0_iter4_reg <= samples_read_reg_637_pp0_iter3_reg;
        samples_read_reg_637_pp0_iter5_reg <= samples_read_reg_637_pp0_iter4_reg;
        samples_read_reg_637_pp0_iter6_reg <= samples_read_reg_637_pp0_iter5_reg;
        samples_read_reg_637_pp0_iter7_reg <= samples_read_reg_637_pp0_iter6_reg;
        samples_read_reg_637_pp0_iter8_reg <= samples_read_reg_637_pp0_iter7_reg;
        samples_read_reg_637_pp0_iter9_reg <= samples_read_reg_637_pp0_iter8_reg;
        sine_lut_load_reg_693 <= sine_lut_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (or_ln49_reg_657 == 1'd1))) begin
        accumulators_load112_fu_142 <= accumulators_q1;
        gmem_addr_1_read411_fu_138 <= gmem_0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_condition_exit_pp0_iter0_stage0_pp0_iter1_reg <= ap_condition_exit_pp0_iter0_stage0;
        ap_condition_exit_pp0_iter0_stage0_pp0_iter2_reg <= ap_condition_exit_pp0_iter0_stage0_pp0_iter1_reg;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        ap_loop_init_pp0_iter1_reg <= ap_loop_init;
        ap_loop_init_pp0_iter2_reg <= ap_loop_init_pp0_iter1_reg;
        first_iter_0_reg_220_pp0_iter1_reg <= first_iter_0_reg_220;
        icmp_ln47_reg_647 <= icmp_ln47_fu_304_p2;
        icmp_ln47_reg_647_pp0_iter1_reg <= icmp_ln47_reg_647;
        phaseInc_read_reg_642 <= phaseInc;
        samples_read_reg_637 <= samples;
        samples_read_reg_637_pp0_iter1_reg <= samples_read_reg_637;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter1_accumulators_load3_reg_243 <= ap_phi_reg_pp0_iter0_accumulators_load3_reg_243;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter2_accumulators_load3_reg_243 <= ap_phi_reg_pp0_iter1_accumulators_load3_reg_243;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter3_accumulators_load3_reg_243 <= ap_phi_reg_pp0_iter2_accumulators_load3_reg_243;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter4_accumulators_load3_reg_243 <= ap_phi_reg_pp0_iter3_accumulators_load3_reg_243;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter5_accumulators_load3_reg_243 <= ap_phi_reg_pp0_iter4_accumulators_load3_reg_243;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter6_accumulators_load3_reg_243 <= ap_phi_reg_pp0_iter5_accumulators_load3_reg_243;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter7_accumulators_load3_reg_243 <= ap_phi_reg_pp0_iter6_accumulators_load3_reg_243;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter8_accumulators_load3_reg_243 <= ap_phi_reg_pp0_iter7_accumulators_load3_reg_243;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter9_accumulators_load3_reg_243 <= ap_phi_reg_pp0_iter8_accumulators_load3_reg_243;
        icmp_ln50_reg_667 <= icmp_ln50_fu_409_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        empty_fu_146 <= add_ln52_1_fu_488_p2;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        accumulators_ce0_local = 1'b1;
    end else begin
        accumulators_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        accumulators_ce1_local = 1'b1;
    end else begin
        accumulators_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (icmp_ln50_reg_667_pp0_iter9_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        accumulators_we0_local = 1'b1;
    end else begin
        accumulators_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln47_fu_304_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter18_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_condition_exit_pp0_iter0_stage0_pp0_iter8_reg) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_loop_exit_ready_delayed = 1'b1;
    end else begin
        ap_loop_exit_ready_delayed = 1'b0;
    end
end

always @ (*) begin
    if ((or_ln49_reg_657_pp0_iter9_reg == 1'd0)) begin
        ap_phi_mux_accumulators_load3_phi_fu_246_p4 = empty_fu_146;
    end else begin
        ap_phi_mux_accumulators_load3_phi_fu_246_p4 = ap_phi_reg_pp0_iter10_accumulators_load3_reg_243;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (icmp_ln47_reg_647_pp0_iter8_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_icmp_ln5015_phi_fu_236_p4 = icmp_ln50_reg_667;
    end else if ((ap_loop_init_pp0_iter8_reg == 1'b1)) begin
        ap_phi_mux_icmp_ln5015_phi_fu_236_p4 = 1'd0;
    end else begin
        ap_phi_mux_icmp_ln5015_phi_fu_236_p4 = icmp_ln50_reg_667;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten7_load = 9'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten7_load = indvar_flatten7_fu_106;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten7_load_1 = 9'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten7_load_1 = indvar_flatten7_fu_106;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (first_iter_0_reg_220 == 1'd1))) begin
        gmem_0_ARVALID = 1'b1;
    end else begin
        gmem_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (first_iter_0_reg_220_pp0_iter11_reg == 1'd1))) begin
        gmem_0_AWVALID = 1'b1;
    end else begin
        gmem_0_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln47_reg_647_pp0_iter17_reg == 1'd1))) begin
        gmem_0_BREADY = 1'b1;
    end else begin
        gmem_0_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (or_ln49_reg_657 == 1'd1))) begin
        gmem_0_RREADY = 1'b1;
    end else begin
        gmem_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        gmem_0_WVALID = 1'b1;
    end else begin
        gmem_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (first_iter_0_reg_220 == 1'd1))) begin
        gmem_blk_n_AR = m_axi_gmem_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (first_iter_0_reg_220_pp0_iter11_reg == 1'd1))) begin
        gmem_blk_n_AW = m_axi_gmem_AWREADY;
    end else begin
        gmem_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln47_reg_647_pp0_iter17_reg == 1'd1))) begin
        gmem_blk_n_B = m_axi_gmem_BVALID;
    end else begin
        gmem_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (or_ln49_reg_657 == 1'd1))) begin
        gmem_blk_n_R = m_axi_gmem_RVALID;
    end else begin
        gmem_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem_blk_n_W = m_axi_gmem_WREADY;
    end else begin
        gmem_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        sine_lut_ce0_local = 1'b1;
    end else begin
        sine_lut_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign accumulators_address1 = i_cast_cast_fu_390_p1;

assign add_ln47_1_fu_421_p2 = (select_ln47_2_fu_378_p3 + 9'd48);

assign add_ln47_2_fu_295_p2 = (ap_sig_allocacmp_indvar_flatten7_load + 9'd1);

assign add_ln47_fu_415_p2 = (i_fu_362_p3 + 4'd1);

assign add_ln50_fu_522_p2 = (accumulators_load112_fu_142 + sub_ln50_fu_516_p2);

assign add_ln52_1_fu_488_p2 = (gmem_addr_1_read411_fu_138 + ap_phi_mux_accumulators_load3_phi_fu_246_p4);

assign add_ln52_fu_427_p2 = (sineIdx_fu_370_p3 + 9'd48);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b1 == ap_block_state19_pp0_stage0_iter18)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage0_iter9)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b1 == ap_block_state19_pp0_stage0_iter18)) | ((gmem_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b1)) | ((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b1 == ap_block_state13_io)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage0_iter9)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_io)));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b1 == ap_block_state19_pp0_stage0_iter18)) | ((gmem_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b1)) | ((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b1 == ap_block_state13_io)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage0_iter9)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_io)));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state10_pp0_stage0_iter9 = ((or_ln49_reg_657 == 1'd1) & (gmem_0_RVALID == 1'b0));
end

always @ (*) begin
    ap_block_state13_io = ((gmem_0_AWREADY == 1'b0) & (first_iter_0_reg_220_pp0_iter11_reg == 1'd1));
end

always @ (*) begin
    ap_block_state19_pp0_stage0_iter18 = ((icmp_ln47_reg_647_pp0_iter17_reg == 1'd1) & (gmem_0_BVALID == 1'b0));
end

always @ (*) begin
    ap_block_state2_io = ((first_iter_0_reg_220 == 1'd1) & (gmem_0_ARREADY == 1'b0));
end

always @ (*) begin
    ap_condition_598 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001));
end

always @ (*) begin
    ap_condition_649 = ((ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_889 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln47_reg_647 == 1'd0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_accumulators_load3_reg_243 = 'bx;

assign ap_ready = ap_ready_sig;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign empty_19_fu_386_p1 = i_fu_362_p3[2:0];

assign gmem_0_WDATA = sine_lut_load_reg_693;

assign i_cast_cast_fu_390_p1 = empty_19_fu_386_p1;

assign i_fu_362_p3 = ((ap_phi_mux_icmp_ln5015_phi_fu_236_p4[0:0] == 1'b1) ? add_ln4716_fu_126 : i8_fu_110);

assign icmp_ln47_fu_304_p2 = ((ap_sig_allocacmp_indvar_flatten7_load_1 == 9'd383) ? 1'b1 : 1'b0);

assign icmp_ln50_fu_409_p2 = ((sineIdx_2_fu_403_p2 == select_ln47_2_fu_378_p3) ? 1'b1 : 1'b0);

assign or_ln49_fu_356_p2 = (first_iter_0_reg_220_pp0_iter7_reg | ap_phi_mux_icmp_ln5015_phi_fu_236_p4);

assign select_ln47_2_fu_378_p3 = ((ap_phi_mux_icmp_ln5015_phi_fu_236_p4[0:0] == 1'b1) ? add_ln47_117_fu_130 : indvars_iv710_fu_118);

assign select_ln49_fu_395_p3 = ((ap_phi_mux_icmp_ln5015_phi_fu_236_p4[0:0] == 1'b1) ? add_ln5218_fu_134 : sineIdx_114_fu_122);

assign sext_ln47_1_fu_324_p1 = $signed(trunc_ln47_1_fu_315_p4);

assign sext_ln47_fu_547_p1 = $signed(trunc_ln_fu_538_p4);

assign shl_ln50_1_fu_510_p2 = gmem_addr_1_read411_fu_138 << 32'd4;

assign shl_ln50_fu_504_p2 = gmem_addr_1_read411_fu_138 << 32'd6;

assign sineIdx_2_fu_403_p2 = (select_ln49_fu_395_p3 + 9'd1);

assign sineIdx_fu_370_p3 = ((ap_phi_mux_icmp_ln5015_phi_fu_236_p4[0:0] == 1'b1) ? add_ln5218_fu_134 : sineIdx9_fu_114);

assign sine_lut_address0 = zext_ln54_fu_534_p1;

assign sub_ln50_fu_516_p2 = (shl_ln50_fu_504_p2 - shl_ln50_1_fu_510_p2);

assign trunc_ln47_1_fu_315_p4 = {{phaseInc_read_reg_642[31:2]}};

assign trunc_ln_fu_538_p4 = {{samples_read_reg_637_pp0_iter11_reg[31:2]}};

assign zext_ln54_fu_534_p1 = address_reg_677;

endmodule //MultiSineMaster
