
 PARAMETER VERSION = 2.2.0


BEGIN OS
 PARAMETER OS_NAME = standalone
 PARAMETER OS_VER = 9.2
 PARAMETER PROC_INSTANCE = processor_microblaze_0
 PARAMETER stdin = outputs_axi_uartlite_0
 PARAMETER stdout = outputs_axi_uartlite_0
END


BEGIN PROCESSOR
 PARAMETER DRIVER_NAME = cpu
 PARAMETER DRIVER_VER = 2.18
 PARAMETER HW_INSTANCE = processor_microblaze_0
END


BEGIN DRIVER
 PARAMETER DRIVER_NAME = MultiSine
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = audio_components_MultiSine_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = SimpleSineMaster
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = audio_components_SimpleSineMaster_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = SimpleSine
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = audio_components_SimpleSine_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 4.11
 PARAMETER HW_INSTANCE = audio_components_audio_bram_audio_bram_axi_bram_ctrl_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = axicdma
 PARAMETER DRIVER_VER = 4.14
 PARAMETER HW_INSTANCE = audio_components_audio_bram_axi_cdma_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = emc
 PARAMETER DRIVER_VER = 4.4
 PARAMETER HW_INSTANCE = memory_emc_memory_axi_emc_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 4.11
 PARAMETER HW_INSTANCE = memory_microblaze_0_local_memory_dlmb_bram_if_cntlr
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 4.11
 PARAMETER HW_INSTANCE = memory_microblaze_0_local_memory_ilmb_bram_if_cntlr
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 3.1
 PARAMETER HW_INSTANCE = outputs_AxisToI2sFifo_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = gpio
 PARAMETER DRIVER_VER = 4.12
 PARAMETER HW_INSTANCE = outputs_axi_gpio_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = uartlite
 PARAMETER DRIVER_VER = 3.11
 PARAMETER HW_INSTANCE = outputs_axi_uartlite_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = tmrctr
 PARAMETER DRIVER_VER = 4.13
 PARAMETER HW_INSTANCE = processor_axi_timer_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = intc
 PARAMETER DRIVER_VER = 3.19
 PARAMETER HW_INSTANCE = processor_microblaze_0_axi_intc
END


