
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2024.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2025 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xsimplesinestreambidirectional.h"

/*
* The configuration table for devices
*/

XSimplesinestreambidirectional_Config XSimplesinestreambidirectional_ConfigTable[XPAR_XSIMPLESINESTREAMBIDIRECTIONAL_NUM_INSTANCES] =
{
	{
		XPAR_AUDIO_COMPONENTS_SIMPLESINESTREAMBI_0_DEVICE_ID,
		XPAR_AUDIO_COMPONENTS_SIMPLESINESTREAMBI_0_S_AXI_CONTROL_BASEADDR
	}
};


