// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="SimpleSineStreamBidirectional_SimpleSineStreamBidirectional,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.959000,HLS_SYN_LAT=55,HLS_SYN_TPT=none,HLS_SYN_MEM=6,HLS_SYN_DSP=0,HLS_SYN_FF=178,HLS_SYN_LUT=262,HLS_VERSION=2024_2}" *)

module SimpleSineStreamBidirectional (
        ap_clk,
        ap_rst_n,
        inputs_TDATA,
        inputs_TVALID,
        inputs_TREADY,
        outputs_TDATA,
        outputs_TVALID,
        outputs_TREADY
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst_n;
input  [31:0] inputs_TDATA;
input   inputs_TVALID;
output   inputs_TREADY;
output  [31:0] outputs_TDATA;
output   outputs_TVALID;
input   outputs_TREADY;

 reg    ap_rst_n_inv;
reg    inputs_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    ap_CS_fsm_state2;
reg    outputs_TDATA_blk_n;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg   [31:0] accumulator_reg_85;
reg   [31:0] phaseInc_reg_91;
wire   [31:0] add_ln44_fu_80_p2;
reg   [31:0] add_ln44_reg_96;
wire    grp_SimpleSineStreamBidirectional_Pipeline_VITIS_LOOP_44_1_fu_51_ap_start;
wire    grp_SimpleSineStreamBidirectional_Pipeline_VITIS_LOOP_44_1_fu_51_ap_done;
wire    grp_SimpleSineStreamBidirectional_Pipeline_VITIS_LOOP_44_1_fu_51_ap_idle;
wire    grp_SimpleSineStreamBidirectional_Pipeline_VITIS_LOOP_44_1_fu_51_ap_ready;
wire    grp_SimpleSineStreamBidirectional_Pipeline_VITIS_LOOP_44_1_fu_51_outputs_TREADY;
wire   [31:0] grp_SimpleSineStreamBidirectional_Pipeline_VITIS_LOOP_44_1_fu_51_outputs_TDATA;
wire    grp_SimpleSineStreamBidirectional_Pipeline_VITIS_LOOP_44_1_fu_51_outputs_TVALID;
reg    grp_SimpleSineStreamBidirectional_Pipeline_VITIS_LOOP_44_1_fu_51_ap_start_reg;
wire    ap_CS_fsm_state3;
reg   [31:0] outputs_TDATA_reg;
wire   [31:0] shl_ln44_fu_62_p2;
wire   [31:0] shl_ln44_1_fu_68_p2;
wire   [31:0] sub_ln44_fu_74_p2;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    regslice_both_outputs_U_apdone_blk;
reg    ap_block_state5;
wire    regslice_both_inputs_U_apdone_blk;
wire   [31:0] inputs_TDATA_int_regslice;
wire    inputs_TVALID_int_regslice;
reg    inputs_TREADY_int_regslice;
wire    regslice_both_inputs_U_ack_in;
reg   [31:0] outputs_TDATA_int_regslice;
reg    outputs_TVALID_int_regslice;
wire    outputs_TREADY_int_regslice;
wire    regslice_both_outputs_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 grp_SimpleSineStreamBidirectional_Pipeline_VITIS_LOOP_44_1_fu_51_ap_start_reg = 1'b0;
end

SimpleSineStreamBidirectional_SimpleSineStreamBidirectional_Pipeline_VITIS_LOOP_44_1 grp_SimpleSineStreamBidirectional_Pipeline_VITIS_LOOP_44_1_fu_51(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_SimpleSineStreamBidirectional_Pipeline_VITIS_LOOP_44_1_fu_51_ap_start),
    .ap_done(grp_SimpleSineStreamBidirectional_Pipeline_VITIS_LOOP_44_1_fu_51_ap_done),
    .ap_idle(grp_SimpleSineStreamBidirectional_Pipeline_VITIS_LOOP_44_1_fu_51_ap_idle),
    .ap_ready(grp_SimpleSineStreamBidirectional_Pipeline_VITIS_LOOP_44_1_fu_51_ap_ready),
    .outputs_TREADY(grp_SimpleSineStreamBidirectional_Pipeline_VITIS_LOOP_44_1_fu_51_outputs_TREADY),
    .accumulator(accumulator_reg_85),
    .phaseInc(phaseInc_reg_91),
    .outputs_TDATA(grp_SimpleSineStreamBidirectional_Pipeline_VITIS_LOOP_44_1_fu_51_outputs_TDATA),
    .outputs_TVALID(grp_SimpleSineStreamBidirectional_Pipeline_VITIS_LOOP_44_1_fu_51_outputs_TVALID)
);

SimpleSineStreamBidirectional_regslice_both #(
    .DataWidth( 32 ))
regslice_both_inputs_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inputs_TDATA),
    .vld_in(inputs_TVALID),
    .ack_in(regslice_both_inputs_U_ack_in),
    .data_out(inputs_TDATA_int_regslice),
    .vld_out(inputs_TVALID_int_regslice),
    .ack_out(inputs_TREADY_int_regslice),
    .apdone_blk(regslice_both_inputs_U_apdone_blk)
);

SimpleSineStreamBidirectional_regslice_both #(
    .DataWidth( 32 ))
regslice_both_outputs_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(outputs_TDATA_int_regslice),
    .vld_in(outputs_TVALID_int_regslice),
    .ack_in(outputs_TREADY_int_regslice),
    .data_out(outputs_TDATA),
    .vld_out(regslice_both_outputs_U_vld_out),
    .ack_out(outputs_TREADY),
    .apdone_blk(regslice_both_outputs_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_SimpleSineStreamBidirectional_Pipeline_VITIS_LOOP_44_1_fu_51_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (inputs_TVALID_int_regslice == 1'b1))) begin
            grp_SimpleSineStreamBidirectional_Pipeline_VITIS_LOOP_44_1_fu_51_ap_start_reg <= 1'b1;
        end else if ((grp_SimpleSineStreamBidirectional_Pipeline_VITIS_LOOP_44_1_fu_51_ap_ready == 1'b1)) begin
            grp_SimpleSineStreamBidirectional_Pipeline_VITIS_LOOP_44_1_fu_51_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        accumulator_reg_85 <= inputs_TDATA_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln44_reg_96 <= add_ln44_fu_80_p2;
        phaseInc_reg_91 <= inputs_TDATA_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_SimpleSineStreamBidirectional_Pipeline_VITIS_LOOP_44_1_fu_51_outputs_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        outputs_TDATA_reg <= grp_SimpleSineStreamBidirectional_Pipeline_VITIS_LOOP_44_1_fu_51_outputs_TDATA;
    end
end

always @ (*) begin
    if ((inputs_TVALID_int_regslice == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((inputs_TVALID_int_regslice == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_SimpleSineStreamBidirectional_Pipeline_VITIS_LOOP_44_1_fu_51_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((outputs_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state5)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        inputs_TDATA_blk_n = inputs_TVALID_int_regslice;
    end else begin
        inputs_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state2) & (inputs_TVALID_int_regslice == 1'b1)) | ((1'b1 == ap_CS_fsm_state1) & (inputs_TVALID_int_regslice == 1'b1)))) begin
        inputs_TREADY_int_regslice = 1'b1;
    end else begin
        inputs_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        outputs_TDATA_blk_n = outputs_TREADY_int_regslice;
    end else begin
        outputs_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (outputs_TREADY_int_regslice == 1'b1))) begin
        outputs_TDATA_int_regslice = add_ln44_reg_96;
    end else if (((grp_SimpleSineStreamBidirectional_Pipeline_VITIS_LOOP_44_1_fu_51_outputs_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        outputs_TDATA_int_regslice = grp_SimpleSineStreamBidirectional_Pipeline_VITIS_LOOP_44_1_fu_51_outputs_TDATA;
    end else begin
        outputs_TDATA_int_regslice = outputs_TDATA_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (outputs_TREADY_int_regslice == 1'b1))) begin
        outputs_TVALID_int_regslice = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        outputs_TVALID_int_regslice = grp_SimpleSineStreamBidirectional_Pipeline_VITIS_LOOP_44_1_fu_51_outputs_TVALID;
    end else begin
        outputs_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (inputs_TVALID_int_regslice == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (inputs_TVALID_int_regslice == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_SimpleSineStreamBidirectional_Pipeline_VITIS_LOOP_44_1_fu_51_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (outputs_TREADY_int_regslice == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (1'b0 == ap_block_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln44_fu_80_p2 = (accumulator_reg_85 + sub_ln44_fu_74_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state5 = ((outputs_TREADY_int_regslice == 1'b0) | (regslice_both_outputs_U_apdone_blk == 1'b1));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_SimpleSineStreamBidirectional_Pipeline_VITIS_LOOP_44_1_fu_51_ap_start = grp_SimpleSineStreamBidirectional_Pipeline_VITIS_LOOP_44_1_fu_51_ap_start_reg;

assign grp_SimpleSineStreamBidirectional_Pipeline_VITIS_LOOP_44_1_fu_51_outputs_TREADY = (outputs_TREADY_int_regslice & ap_CS_fsm_state3);

assign inputs_TREADY = regslice_both_inputs_U_ack_in;

assign outputs_TVALID = regslice_both_outputs_U_vld_out;

assign shl_ln44_1_fu_68_p2 = inputs_TDATA_int_regslice << 32'd4;

assign shl_ln44_fu_62_p2 = inputs_TDATA_int_regslice << 32'd6;

assign sub_ln44_fu_74_p2 = (shl_ln44_fu_62_p2 - shl_ln44_1_fu_68_p2);

endmodule //SimpleSineStreamBidirectional
